---
permalink: config-linux/index.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Nutzen Sie die Express-Konfiguration für einen Linux-Host mit einem E-Series System. 
---
= Überblick über die Konfiguration von Linux Express
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Linux Express-Methode zur Installation Ihres Storage-Arrays und zum Zugriff auf SANtricity System Manager ist zur Einrichtung eines eigenständigen Linux-Hosts auf einem E-Series Storage-System geeignet. Er ist so konzipiert, dass das Storage-System mit minimalen Entscheidungspunkten schneller betriebsbereit ist.



== Verfahrensübersicht

Die Linux Express-Methode umfasst die folgenden Schritte.

. Richten Sie eine der folgenden Kommunikationsumgebungen ein:
+
** Fibre Channel (FC)
** ISCSI
** SAS
** ISER-over-InfiniBand
** SRP über InfiniBand
** NVMe über Infiniband
** NVMe over RoCE
** NVMe over Fibre Channel


. Erstellung logischer Volumes im Storage-Array
. Stellen Sie die Volumes für den Daten-Host zur Verfügung.




== Weitere Informationen

* Online-Hilfe – beschreibt die Verwendung von SANtricity System Manager zum Abschließen von Konfigurations- und Storage-Managementaufgaben. Es ist im Produkt verfügbar.
* https://kb.netapp.com/["NetApp Knowledge Base"^] (Eine Datenbank mit Artikeln) – enthält Informationen zur Fehlerbehebung, häufig gestellte Fragen und Anweisungen zu einem breiten Spektrum an NetApp Produkten und Technologien.
* http://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^] -- ermöglicht die Suche nach Konfigurationen von NetApp Produkten und Komponenten, die den von NetApp angegebenen Standards und Anforderungen entsprechen.
* https://docs.netapp.com/us-en/ontap-sanhost/hu_luhu_71.html#recommended-driver-settings-with-linux-kernel["Installieren Sie Linux Unified Host Utilities 7.1"^] -- beschreibt die Installation der Linux Unified Host Utilities 7.1.

