---
permalink: config-linux/iscsi-configure-switches-concept.html 
sidebar: sidebar 
keywords: Switches, zoning, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Konfigurieren Sie die Switches entsprechend den Empfehlungen des Anbieters für iSCSI. 
---
= Konfigurieren Sie die Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie konfigurieren die Switches entsprechend den Empfehlungen des Anbieters für iSCSI. Diese Empfehlungen können sowohl Konfigurationsrichtlinien als auch Code-Updates enthalten.

Sie müssen Folgendes sicherstellen:

* Für Hochverfügbarkeit gibt es zwei separate Netzwerke. Vergewissern Sie sich, dass Sie den iSCSI-Datenverkehr in getrennten Netzwerksegmenten isolieren.
* Sie müssen die Flusskontrolle *Ende bis Ende* aktivieren.
* Falls erforderlich, haben Sie Jumbo Frames aktiviert.



NOTE: Port-Kanäle/LACP werden von den Switch-Ports des Controllers nicht unterstützt. Host-seitiges LACP wird nicht empfohlen; Multipathing bietet dieselben Vorteile und in einigen Fällen auch bessere Vorteile.
