---
permalink: config-linux/nvme-roce-verify-linux-config-support-task.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'Um einen zuverlässigen Betrieb zu gewährleisten, erstellen Sie einen Implementierungsplan und überprüfen mit dem NetApp Interoperabilitäts-Matrix-Tool (IMT) die Unterstützung der gesamten Konfiguration.' 
---
= Unterstützung von Linux-Konfigurationen prüfen und Einschränkungen bei E-Series (NVMe over RoCE) prüfen
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Als ersten Schritt sollten Sie überprüfen, ob Ihre Linux-Konfiguration unterstützt wird, und auch die Einschränkungen für Controller, Switch, Host und Recovery prüfen.



== Überprüfen Sie, ob die Linux-Konfiguration unterstützt wird

Um einen zuverlässigen Betrieb zu gewährleisten, erstellen Sie einen Implementierungsplan und überprüfen mit dem NetApp Interoperabilitäts-Matrix-Tool (IMT) die Unterstützung der gesamten Konfiguration.

.Schritte
. Wechseln Sie zum https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].
. Klicken Sie auf die Kachel * Solution Search*.
. Klicken Sie im Menü:Protokolle[SAN Host] auf die Schaltfläche *Hinzufügen* neben *E-Series SAN-Host*.
. Klicken Sie Auf *Suchkriterien Verfeinern*.
+
Der Abschnitt Suchkriterien verfeinern wird angezeigt. In diesem Abschnitt können Sie das zutreffende Protokoll sowie andere Kriterien für die Konfiguration auswählen, z. B. Betriebssystem, NetApp OS und Host Multipath-Treiber.

. Wählen Sie die Kriterien aus, die Sie für Ihre Konfiguration kennen, und sehen Sie dann, welche kompatiblen Konfigurationselemente gelten.
. Führen Sie bei Bedarf die Updates für Ihr Betriebssystem und Protokoll durch, die im Tool vorgeschrieben sind.
+
Detaillierte Informationen zu der von Ihnen gewählten Konfiguration finden Sie auf der Seite Unterstützte Konfigurationen anzeigen, indem Sie auf den rechten Seitenpfeil klicken.





== NVMe over RoCE-Einschränkungen überprüfen

Informationen zur Verwendung von NVMe over RoCE finden Sie im https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^] Um die aktuellen Einschränkungen hinsichtlich Controller, Host und Recovery zu prüfen.



=== Einschränkungen für Switches


CAUTION: *RISIKO EINES DATENVERLUSTS.* Sie müssen die Flusskontrolle zur Verwendung mit Global Pause Control auf dem Switch aktivieren, um das Risiko eines Datenverlusts in einer NVMe over RoCE Umgebung zu beseitigen.



=== Einschränkungen bei Storage und Disaster Recovery

* Asynchrones und synchrones Spiegeln werden nicht unterstützt.
* Thin Provisioning (die Erstellung von Thin Volumes) wird nicht unterstützt.

