---
permalink: config-linux/nvme-tcp-configure-storage-connections-task.html 
sidebar: sidebar 
keywords: NVMe over TCP, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Wenn Ihr Controller eine Verbindung für NVMe over TCP umfasst, können Sie die NVMe Porteinstellungen auf der Hardware-Seite oder der System-Seite in SANtricity System Manager konfigurieren. 
---
= Konfigurieren von Storage Arrays für NVMe over TCP Verbindungen in der E-Series unter Linux
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Ihr Controller eine Verbindung für NVMe over TCP umfasst, können Sie die NVMe Porteinstellungen auf der Hardware-Seite oder der System-Seite in SANtricity System Manager konfigurieren.

.Bevor Sie beginnen
Stellen Sie sicher, dass Sie Folgendes haben:

* Ein NVMe over TCP Host-Port an Ihrem Controller; andernfalls sind die NVMe over TCP Einstellungen in System Manager nicht verfügbar.
* Die IP-Adresse der Hostverbindung.


.Über diese Aufgabe
Auf die NVMe over TCP Konfiguration können Sie über die Seite *Hardware* oder über das Menü:Settings[System] zugreifen. Diese Aufgabe beschreibt, wie die Ports auf der Seite *Hardware* konfiguriert werden.


NOTE: Die Einstellungen und Funktionen für NVMe over TCP werden nur angezeigt, wenn der Controller Ihres Speichersystems über einen NVMe over TCP Port verfügt.

.Schritte
. Wählen Sie im linken Bereich der System Manager-Oberfläche *Hardware* aus.
. Wählen Sie den Controller mit dem NVMe over TCP Port aus, der konfiguriert werden soll.
+
Das Kontextmenü des Controllers wird angezeigt.

. *NVMe über TCP-Ports konfigurieren* wird ausgewählt.
+
Das Dialogfeld *NVMe über TCP Ports konfigurieren* wird geöffnet.

. Wählen Sie in der Dropdown-Liste den Port aus, den Sie konfigurieren möchten, und klicken Sie dann auf *Weiter*.
. Wählen Sie die zu verwendenden Portkonfigurationseinstellungen aus, und klicken Sie dann auf *Weiter*.
+
Um alle Porteinstellungen anzuzeigen, klicken Sie rechts im Dialogfeld auf den Link *Weitere Porteinstellungen anzeigen*.

+
|===
| Port-Einstellung | Beschreibung 


 a| 
Konfigurierte Geschwindigkeit des ethernet-Ports
 a| 
Die gewünschte Geschwindigkeit wird ausgewählt. Die in der Dropdown-Liste angezeigten Optionen hängen von der maximalen Geschwindigkeit ab, die Ihr Netzwerk unterstützt (z. B. 10 Gbit/s). Mögliche Werte sind:

** Autom. Aushandlung
** 10 Gbit/S
** 25 Gbit/S
** 40 Gbit/S
** 50 Gbit/S
** 100 Gbit/S
** 200 Gbit/S



NOTE: Die konfigurierte NVMe over TCP Portgeschwindigkeit sollte der Geschwindigkeitskapazität des SFP am ausgewählten Port entsprechen.



 a| 
Konfigurierter Forward Error Correction (FEC)-Modus
 a| 
Der gewünschte FEC-Modus ist auszuwählen. Die in der Dropdown-Liste angezeigten Optionen hängen von der aktuell ausgewählten Geschwindigkeit ab und führen nur die für diese Geschwindigkeit unterstützten Optionen auf. Nicht alle FEC-Modi sind für alle Geschwindigkeiten verfügbar. Mögliche Werte sind:

** Keine
** Reed-Solomon
** Brandschutzbestimmungen
** Automatisch




 a| 
Aktivieren Sie IPv4 und/oder aktivieren Sie IPv6
 a| 
Wählen Sie eine oder beide Optionen aus, um die Unterstützung für IPv4- und IPv6-Netzwerke zu aktivieren.



 a| 
MTU-Größe (verfügbar durch Klicken auf *Weitere Porteinstellungen anzeigen*.)
 a| 
Geben Sie bei Bedarf eine neue Größe in Byte für die maximale Übertragungseinheit (MTU) ein. Die MTU-Standardgröße beträgt 1500 Byte pro Frame. Sie müssen einen Wert zwischen 1500 und 9000 eingeben.

|===
+
Wenn Sie *IPv4 aktivieren* ausgewählt haben, wird ein Dialogfeld zur Auswahl von IPv4-Einstellungen geöffnet, nachdem Sie auf *Weiter* geklickt haben. Wenn Sie *IPv6* aktivieren ausgewählt haben, wird ein Dialogfeld zur Auswahl von IPv6-Einstellungen geöffnet, nachdem Sie auf *Weiter* geklickt haben. Wenn Sie beide Optionen ausgewählt haben, wird zuerst das Dialogfeld für IPv4-Einstellungen geöffnet, und nach dem Klicken auf *Weiter* wird das Dialogfeld für IPv6-Einstellungen geöffnet.

. Konfigurieren Sie die IPv4- und/oder IPv6-Einstellungen automatisch oder manuell. Um alle Porteinstellungen anzuzeigen, klicken Sie rechts im Dialogfeld auf den Link *Weitere Einstellungen anzeigen*.
+
|===
| Port-Einstellung | Beschreibung 


 a| 
Konfiguration automatisch vom DHCP-Server beziehen
 a| 
Wählen Sie diese Option aus, um die Konfiguration automatisch abzurufen.



 a| 
Statische Konfiguration manuell festlegen
 a| 
Wählen Sie diese Option aus, und geben Sie dann eine statische Adresse in die Felder ein. Geben Sie bei IPv4 die Subnetzmaske und das Gateway des Netzwerks an. Geben Sie für IPv6 die routingfähigen IP-Adressen und die Router-IP-Adresse ein.


NOTE: Wenn nur eine routingfähige IP-Adresse vorhanden ist, setzen Sie die verbleibende Adresse auf 0:0:0:0:0:0:0:0:0.



 a| 
Aktivieren Sie die VLAN-Unterstützung (verfügbar durch Klicken auf *Weitere Einstellungen anzeigen*.)
 a| 

NOTE: Diese Option ist nur in einer iSCSI-Umgebung verfügbar. Sie ist in einer NVMe über TCP Umgebung nicht verfügbar.



 a| 
ethernet-Priorität aktivieren (verfügbar durch Klicken auf *Weitere Einstellungen anzeigen*.)
 a| 

NOTE: Diese Option ist nur in einer iSCSI-Umgebung verfügbar. Sie ist in einer NVMe über TCP Umgebung nicht verfügbar.

|===
. Klicken Sie Auf *Fertig Stellen*.


.Was kommt als Nächstes?
Nachdem Sie die NVMe over TCP Porteinstellungen konfiguriert haben, link:nvme-tcp-discover-connect-storage-host-task.html["Speicher auf dem Host ermitteln und verbinden"].
