---
permalink: config-linux/nvme-tcp-setup-host-side-task.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Die NVMe Initiator Konfiguration in einer TCP-Umgebung umfasst die Installation und Konfiguration des nvme-cli-Pakets, die Konfiguration der Initiator-IP-Adressen und die Einrichtung der NVMe-oF-Schicht auf dem Host. 
---
= Einrichtung des NVMe over TCP Initiators auf einem E-Series Linux Host
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die NVMe Initiator Konfiguration in einer TCP-Umgebung umfasst die Installation und Konfiguration des nvme-cli-Pakets, die Konfiguration der Initiator-IP-Adressen und die Einrichtung der NVMe-oF-Schicht auf dem Host.

.Bevor Sie beginnen
Sie müssen das neueste kompatible Betriebssystem RHEL 9, RHEL 10, SLES 15 oder SLES 16 mit Service Pack ausführen. Siehe die https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^] für eine vollständige Liste der aktuellen Anforderungen.

.Schritte
. Wenn Sie den mitgelieferten Ethernet-Treiber für Ihren HCA verwenden, erfolgt die Installation des  `nvme-cli`Pakets wie folgt:
+
*SLES 15 oder SLES 16*

+
[listing]
----

# zypper install nvme-cli
----
+
*RHEL 9 und RHEL 10*

+
[listing]
----

# yum install nvme-cli
----
+
Wenn Sie eine NVIDIA HCA verwenden und den externen DOCA-Treiber nutzen möchten, finden Sie im link:https://developer.nvidia.com/doca-downloads["NVIDIA-Dokumentation"] Informationen dazu, wie er in dieser Umgebung korrekt installiert wird.

. Für RHEL 9 Netzwerk-Skripte installieren:
+
*RHEL 9*

+
[listing]
----
# yum install NetworkManager-initscripts-updown
----
+

NOTE: Netzwerkskripte sind für RHEL 10 nicht verfügbar.

. Holen Sie den Host-NQN ab, mit dem der Host für ein Array konfiguriert werden kann.
+
[listing]
----
# cat /etc/nvme/hostnqn
----
. IPv4-IP-Adressen werden auf den Ethernet-Ports eingerichtet, die für die Verbindung von NVMe über TCP verwendet werden. Für jede Netzwerkschnittstelle wird ein Konfigurationsskript erstellt, das die verschiedenen Variablen für diese Schnittstelle enthält.
+
Die in diesem Schritt verwendeten Variablen basieren auf der Server-Hardware und der Netzwerkumgebung. Die Variablen enthalten die `IPADDR` Und `GATEWAY`. Dies sind Beispielanweisungen für SLES und RHEL:

+
*SLES 15*

+
Die Beispieldatei  `/etc/sysconfig/network/ifcfg-eth4`wird mit folgendem Inhalt erstellt.

+
[listing]
----
BOOTPROTO='static'
BROADCAST=
ETHTOOL_OPTIONS=
IPADDR='192.168.1.87/24'
GATEWAY='192.168.1.1'
MTU=9000
NAME='<adapter name>'
NETWORK=
REMOTE_IPADDR=
STARTMODE='auto'
----
+
Erstellen Sie dann die Beispieldatei `/etc/sysconfig/network/ifcfg-eth5`:

+
[listing]
----
BOOTPROTO='static'
BROADCAST=
ETHTOOL_OPTIONS=
IPADDR='192.168.2.87/24'
GATEWAY='192.168.2.1'
MTU=9000
NAME='<adapter name>'
NETWORK=
REMOTE_IPADDR=
STARTMODE='auto'
----
+
*RHEL 9, RHEL 10 oder SLES 16*

+
Verwenden Sie die `nmtui` Werkzeug zum Aktivieren und Bearbeiten einer Verbindung. Unten sehen Sie eine Beispieldatei `/etc/NetworkManager/system-connections/eth4.nmconnection` Das Tool generiert Folgendes:

+
[listing]
----

[connection]
id=eth4
uuid=<unique uuid>
type=ethernet
interface-name=eth4

[ethernet]
mtu=9000

[ipv4]
address1=192.168.1.87/24
method=manual

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
----
+
Unten sehen Sie eine Beispieldatei `/etc/NetworkManager/system-connections/eth5.nmconnection` Das Tool generiert Folgendes:

+
[listing]
----

[connection]
id=eth5
uuid=<unique uuid>
type=ethernet
interface-name=eth5

[ethernet]
mtu=9000

[ipv4]
address1=192.168.2.87/24
method=manual

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
----
. Aktivieren der Netzwerkschnittstellen:
+
[listing]
----

# nmcli connection up eth4
# nmcli connection up eth5
----
. Die NVMe-oF-Schicht wird auf dem Host eingerichtet. Die folgende Datei wird unter  `/etc/modules-load.d/` erstellt, um das  `nvme_tcp` Kernelmodul zu laden und sicherzustellen, dass das Kernelmodul auch nach einem Neustart immer aktiv ist:
+
[listing]
----

# cat /etc/modules-load.d/nvme_tcp.conf
  nvme_tcp
----
. Starten Sie den Host neu.
+
.. Alternativ kann das  `nvme_tcp`Kernelmodul auch ohne Neustart durch Ausführen dieses Befehls geladen werden:
+
[listing]
----

# modprobe nvme_tcp
----


. Um zu überprüfen, ob das  `nvme_tcp` Kernelmodul geladen ist, führen Sie diesen Befehl aus:
+
[listing]
----
# lsmod | grep nvme
nvme_tcp               45056  0
nvme_fabrics           24576  1 nvme_tcp
nvme_core             114688  5 nvme_tcp,nvme_fabrics
t10_pi                 16384  2 sd_mod,nvme_core
----
+
.Was kommt als Nächstes?
Nachdem der NVMe over TCP Initiator auf dem Host eingerichtet wurde, link:nvme-tcp-configure-storage-connections-task.html["die NVMe über TCP Porteinstellungen konfigurieren"].


