---
permalink: config-linux/nvme-fc-access-physical-targets-concept.html 
sidebar: sidebar 
keywords: NVMe volumes physical, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Konfigurieren Sie die E/A, die auf dem Geräteziel basiert, basierend auf Ihrer Linux-Version. 
---
= Zugriff auf NVMe Volumes für physische NVMe Geräteziele in der E-Series – Linux (NVMe over FC)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können die zum Geräteziel gerichteten I/O-Vorgänge auf der Grundlage des Betriebssystems (und der Multipathing-Methode der Erweiterung) konfigurieren.

Bei RHEL 8, RHEL 9 und SLES 15 wird I/O vom Linux-Host an die physischen NVMe-Geräteziele geleitet. Bei einer nativen NVMe Multipathing-Lösung werden die physischen Pfade verwaltet, die sich auf dem einzelnen scheinbar physischen Gerät befinden, das vom Host angezeigt wird.



== Physische NVMe Geräte sind I/O-Ziele

Es empfiehlt sich, I/O-Vorgänge zu den Links in auszuführen `/dev/disk/by-id/nvme-eui.[uuid#]` Statt direkt auf den physischen nvme-Gerätepfad zu gelangen `/dev/nvme[subsys#]n[id#]`. Die Verknüpfung zwischen diesen beiden Standorten kann mit folgendem Befehl gefunden werden:

[listing]
----
# ls /dev/disk/by-id/ -l
lrwxrwxrwx 1 root root 13 Oct 18 15:14 nvme-eui.0000320f5cad32cf00a0980000af4112 -> ../../nvme0n1
----
I/O läuft auf `/dev/disk/by-id/nvme-eui.[uuid#]` Wird direkt durchgereicht `/dev/nvme[subsys#]n[id#]` Welches alle darunter virtualisierten Pfade mithilfe der nativen NVMe-Multipathing-Lösung hat.

Sie können Ihre Pfade anzeigen, indem Sie Folgendes ausführen:

[listing]
----
# nvme list-subsys
----
Beispielausgabe:

[listing]
----
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:5700.600a098000a522500000000589aa8a6
\
+- nvme0 rdma traddr=192.4.21.131 trsvcid=4420 live
+- nvme1 rdma traddr=192.4.22.141 trsvcid=4420 live
----
Wenn Sie bei Verwendung des ein Namespace-Gerät angeben `nvme list-subsys` Befehl, es stellt zusätzliche Informationen über die Pfade zu diesem Namespace bereit:

[listing]
----
# nvme list-subsys /dev/nvme0n1
nvme-subsys0 - NQN=nqn.1992-08.com.netapp:5700.600a098000af44620000000058d5dd96
\
 +- nvme0 rdma traddr=192.168.130.101 trsvcid=4420 live non-optimized
 +- nvme1 rdma traddr=192.168.131.101 trsvcid=4420 live non-optimized
 +- nvme2 rdma traddr=192.168.130.102 trsvcid=4420 live optimized
 +- nvme3 rdma traddr=192.168.131.102 trsvcid=4420 live optimized
----
Die Multipath-Befehle sind ebenfalls mit Haken dabei, damit Sie Ihre Pfadinformationen auch für natives Failover anzeigen können. Dazu gehören:

[listing]
----
#multipath -ll
----

NOTE: Um die Pfadinformationen anzuzeigen, muss in Folgendes festgelegt werden `/etc/multipath.conf`:

[listing]
----

defaults {
        enable_foreign nvme
}
----
Beispielausgabe:

[listing]
----
eui.0000a0335c05d57a00a0980000a5229d [nvme]:nvme0n9 NVMe,Netapp E-Series,08520001
size=4194304 features='n/a' hwhandler='ANA' wp=rw
|-+- policy='n/a' prio=50 status=optimized
| `- 0:0:1 nvme0c0n1 0:0 n/a optimized    live
`-+- policy='n/a' prio-10 status=non-optimized
`- 0:1:1 nvme0c1n1 0:0 n/a non-optimized    live
----