---
permalink: config-linux/nvme-ib-discover-connect-storage-host-task.html 
sidebar: sidebar 
keywords: discover storage, host, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Bevor Sie jeden Host in SANtricity System Manager definieren können, müssen Sie die Ziel-Controller-Ports vom Host erkennen und dann NVMe-Verbindungen herstellen. 
---
= Ermitteln und Herstellen einer Verbindung zum Speicher vom Host aus
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie jeden Host in SANtricity System Manager definieren können, müssen Sie die Ziel-Controller-Ports vom Host erkennen und dann NVMe-Verbindungen herstellen.

.Schritte
. Ermitteln Sie mithilfe des folgenden Befehls verfügbare Subsysteme auf dem NVMe-of Ziel für alle Pfade:
+
[listing]
----
nvme discover -t rdma -a target_ip_address
----
+
In diesem Befehl `target_ip_address` Ist die IP-Adresse des Ziel-Ports.

+

NOTE: Der `nvme discover` Der Befehl erkennt alle Controller-Ports im Subsystem, unabhängig vom Host-Zugriff.

+
[listing]
----
# nvme discover -t rdma -a 10.10.10.100
 Discovery Log Number of Records 2, Generation counter 0
 =====Discovery Log Entry 0======
 trtype:  rdma
 adrfam:  ipv4
 subtype: nvme subsystem
 treq:    not specified
 portid:  0
 trsvcid: 4420
 subnqn:  nqn.1992-08.com.netapp:5700.600a098000af41580000000058ed54be
 traddr: 10.10.10.100
 rdma_prtype: infiniband
 rdma_qptype: connected
 rdma_cms:    rdma-cm
 rdma_pkey: 0x0000
=====Discovery Log Entry 1======
 trtype:  rdma
 adrfam:  ipv4
 subtype: nvme subsystem
 treq:    not specified
 portid:  1
 trsvcid: 4420
 subnqn:  nqn.1992-08.com.netapp:5700.600a098000af41580000000058ed54be
 traddr: 11.11.11.100
 rdma_prtype: infiniband
 rdma_qptype: connected
 rdma_cms:    rdma-cm
 rdma_pkey: 0x0000
----
. Wiederholen Sie Schritt 1 für alle anderen Verbindungen.
. Stellen Sie auf dem ersten Pfad eine Verbindung zum erkannten Subsystem her, indem Sie den Befehl verwenden: `nvme connect -t rdma -n discovered_sub_nqn -a target_ip_address -Q queue_depth_setting -l controller_loss_timeout_period`
+

NOTE: Der oben genannte Befehl ist nicht durch ein Neubooten erhalten. Der `nvme connect` Nach jedem Neustart muss der Befehl ausgeführt werden, um die NVMe-Verbindungen wiederherzustellen.

+

NOTE: Die NVMe-Verbindungen bleiben jedoch nicht bestehen, wenn ein System-Reboot oder längere Zeiträume des Controllers nicht verfügbar sind.

+

NOTE: Verbindungen werden nicht für einen entdeckten Port hergestellt, auf den der Host nicht zugreifen kann.

+

NOTE: Wenn Sie mit diesem Befehl eine Portnummer angeben, schlägt die Verbindung fehl. Der Standardport ist der einzige Port, der für Verbindungen eingerichtet ist.

+

NOTE: Die empfohlene Einstellung für die Warteschlangentiefe ist 1024. Überschreiben Sie die Standardeinstellung 128 mit 1024 mit dem ``-Q 1024``Die Befehlszeilenoption, wie im folgenden Beispiel gezeigt.

+

NOTE: Die empfohlene Zeit für den Controller-Verlust beträgt in Sekunden 60 Minuten (3600 Sekunden). Überschreiben Sie die Standardeinstellung von 600 Sekunden mit 3600 Sekunden mit dem `-l 3600` Die Befehlszeilenoption, wie im folgenden Beispiel gezeigt:

+
[listing]
----
# nvme connect -t rdma -a 10.10.10.100 -n nqn.1992-08.com.netapp:5700.600a098000af41580000000058ed54be -Q 1024 -l 3600
----
. Verwenden Sie die `nvme list` Befehl, um eine Liste der derzeit verbundenen NVMe-Geräte anzuzeigen. Im unten stehenden Beispiel ist es `nvme0n1`.
+
[listing]
----
 # nvme list

 Node          SN            Model             Namespace
 -------------------------------------------------------
 /dev/nvme0n1  021648023161  NetApp E-Series      1
----
+
[listing]
----
Usage                 Format           FW Rev
--------------------------------------------------------------
5.37 GB /5.37 GB      512 B + 0 B      0842XXXX
----
. Stellen Sie auf dem zweiten Pfad eine Verbindung zum erkannten Subsystem her:
+
[listing]
----
  # nvme connect -t rdma -a 11.11.11.100 -n nqn.1992-08.com.netapp:5700.600a098000af41580000000058ed54be -Q 1024 -l 3600
----
. Verwenden Sie Linux `lsblk` Und `grep` Befehle, um zusätzliche Informationen zu jedem Blockgerät anzuzeigen:
+
[listing]
----
 # lsblk | grep nvme

 nvme0n1    259:0    0     5G  0 disk
 nvme1n1    259:0    0     5G  0 disk
----
. Verwenden Sie die `nvme list` Befehl, um eine neue Liste der derzeit verbundenen NVMe-Geräte anzuzeigen. Im unten stehenden Beispiel ist es `nvme0n1` Und `nvme0n1`.
+
[listing]
----
 # nvme list
 Node          SN            Model                   Namespace
 -------------------------------------------------------------
 /dev/nvme0n1  021648023161  NetApp E-Series          1
 /dev/nvme1n1  021648023161  NetApp E-Series          1
----
+
[listing]
----
Usage                 Format           FW Rev
--------------------------------------------------------------
5.37 GB /5.37 GB          512 B + 0 B      0842XXXX
5.37 GB /5.37 GB          512 B + 0 B      0842XXXX
----

