---
permalink: config-linux/nvme-roce-setup-failover-host-task.html 
sidebar: sidebar 
keywords: failover, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Konfigurieren Sie den Host für das Failover. 
---
= Failover auf dem Host in E-Series einrichten – Linux (NVMe over RoCE)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um einen redundanten Pfad zum Speicher-Array bereitzustellen, können Sie den Host so konfigurieren, dass ein Failover ausgeführt wird.

.Bevor Sie beginnen
Beachten Sie die  https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^] , um sicherzustellen, dass alle erforderlichen Updates installiert sind, da wichtige Fehlerbehebungen für Versionen von SLES oder RHEL erforderlich sein können, die in der ersten Version nicht verfügbar sind.

.Über diese Aufgabe
Bei SLES 15, SLES 16, RHEL 9 und RHEL 10 ist Native NVMe Multipathing standardmäßig aktiviert und es ist keine zusätzliche Konfiguration erforderlich.

.Was kommt als Nächstes?
Mit aktiviertem nativen NVMe-Multipathing link:nvme-roce-access-physical-targets-concept.html["Zugriff auf die NVMe-Volumes für ein E-Series-Ziel vom Host"].
