---
permalink: config-linux/nvme-fc-create-filesystems-sles-15-task.html 
sidebar: sidebar 
keywords: file systems, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Für RHEL 8 und SLES 15 erstellen Sie ein Dateisystem auf dem nativen nvme-Gerät und mounten das Dateisystem. 
---
= Dateisysteme in E-Series erstellen – Linux RHEL 8, RHEL 9 und SLES 15 (NVMe over FC)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bei RHEL 8, RHEL 9 und SLES 15 erstellen Sie ein Dateisystem auf dem nativen nvme-Gerät und mounten das Dateisystem.

.Schritte
. Führen Sie den Befehl Multipath -ll aus, um eine Liste der nvme Geräte anzuzeigen.
+
[listing]
----
# multipath -ll
----
+
Das Ergebnis dieses Befehls kann verwendet werden, um die zugeordneten Geräte zu finden `/dev/disk/by-id/nvme-eui.[uuid#]` Standort. Für das Beispiel unten wäre dies `/dev/disc/by-id/nvme-eui.000082dd5c05d39300a0980000a52225`.

+
[listing]
----
eui.000082dd5c05d39300a0980000a52225 [nvme]:nvme0n6 NVMe,NetApp E-Series,08520000
size=4194304 features='n/a' hwhandler='ANA' wp=rw
|-+- policy='n/a' prio=50 status=optimized
| `- 0:0:1 nvme0c0n1 0:0 n/a optimized     live
|-+- policy='n/a' prio=50 status=optimized
| `- 0:1:1 nvme0c1n1 0:0 n/a optimized     live
|-+- policy='n/a' prio=10 status=non-optimized
| `- 0:2:1 nvme0c2n1 0:0 n/a non-optimized live
`-+- policy='n/a' prio=10 status=non-optimized
  `- 0:3:1 nvme0c3n1 0:0 n/a non-optimized live
----
. Erstellen Sie ein Dateisystem auf der Partition für das gewünschte nvme-Gerät unter Verwendung des Speicherorts `/dev/disk/by-id/nvme-eui.[id#]`.
+
Die Methode zum Erstellen eines Dateisystems variiert je nach gewähltem Dateisystem. Dieses Beispiel zeigt die Erstellung eines ext4-Dateisystems.

+
[listing]
----
# mkfs.ext4 /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225
mke2fs 1.42.11 (22-Oct-2019)
Creating filesystem with 2620928 4k blocks and 655360 inodes
Filesystem UUID: 97f987e9-47b8-47f7-b434-bf3ebbe826d0
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632

Allocating group tables: done
Writing inode tables: done
Creating journal (32768 blocks): done
Writing superblocks and filesystem accounting information: done
----
. Erstellen Sie einen Ordner, um das neue Gerät zu mounten.
+
[listing]
----
# mkdir /mnt/ext4
----
. Montieren Sie das Gerät.
+
[listing]
----
# mount /dev/disk/by-id/nvme-eui.000082dd5c05d39300a0980000a52225 /mnt/ext4
----

