---
permalink: config-linux/nvme-fc-configure-fc-switches-task.html 
sidebar: sidebar 
keywords: FC switch, zoning, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'Konfigurieren von \(Zoning\) die Fibre Channel \(FC\)-Switches ermöglicht es den Hosts, eine Verbindung zum Storage-Array herzustellen, und begrenzt die Anzahl der Pfade. Sie Zonen der Switches mithilfe der Managementoberfläche für die Switches.' 
---
= Konfigurieren Sie die FC-Switches
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Konfigurieren (Zoning) der Fibre Channel (FC)-Switches ermöglicht es den Hosts, eine Verbindung zum Storage-Array herzustellen, und begrenzt die Anzahl der Pfade. Sie Zonen der Switches mithilfe der Managementoberfläche für die Switches.

.Was Sie benötigen
* Administrator-Anmeldeinformationen für die Switches.
* Der WWPN jedes Host-Initiator-Ports und jedes Controller-Zielports, der mit dem Switch verbunden ist. (Verwenden Sie Ihr HBA Utility für die Erkennung.)


.Über diese Aufgabe
Informationen zum Zoning der Switches finden Sie in der Dokumentation des Switch-Anbieters.

Jeder Initiator-Port muss sich in einer separaten Zone mit allen entsprechenden Ziel-Ports befinden.

.Schritte
. Melden Sie sich beim FC Switch-Administrationsprogramm an und wählen Sie dann die Zoning-Konfigurationsoption aus.
. Erstellen Sie eine neue Zone, die den ersten Host-Initiator-Port enthält, und die auch alle Ziel-Ports umfasst, die mit demselben FC-Switch wie der Initiator verbunden sind.
. Erstellen Sie zusätzliche Zonen für jeden FC-Host-Initiator-Port im Switch.
. Speichern Sie die Zonen, und aktivieren Sie dann die neue Zoning-Konfiguration.

