---
permalink: config-linux/nvme-fc-setup-host-side-task.html 
sidebar: sidebar 
keywords: NVMe over Fibre Channel, host side, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Die NVMe-Initiatorkonfiguration in einer Fibre-Channel-Umgebung umfasst die Installation und Konfiguration des nvme-cli-Pakets sowie die Aktivierung des NVMe/FC-Initiators auf dem Host. 
---
= Richten Sie NVMe over Fibre Channel auf der Host-Seite ein
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die NVMe-Initiatorkonfiguration in einer Fibre-Channel-Umgebung umfasst die Installation und Konfiguration des nvme-cli-Pakets sowie die Aktivierung des NVMe/FC-Initiators auf dem Host.

Folgende Verfahren werden für RHEL 7, RHEL 8, RHEL 9, SLES 12 und SLES 15 unter Verwendung von Broadcom Emulex oder QLogic NVMe/FC-fähigen FC-HBAs beschrieben. Für weitere Informationen darüber, welche Versionen dieser OS oder HBA unterstützt werden, konsultieren Sie die https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].

.Schritte
. Installieren Sie den `nvme-cli` Paket:
+
*SLES 12 oder SLES 15*

+
[listing]
----

# zypper install nvme-cli
----
+
*RHEL 7, RHEL 8 ODER RHEL 9*

+
[listing]
----

# yum install nvme-cli
----
+
.. Laden Sie nur für RHEL 7 ein externes Broadcom Autoconnect-Skript für NVMe/FC-Verbindungen über das herunter, und installieren Sie es https://www.broadcom.com/support/download-search["Broadcom Website"^]. Geben Sie das Stichwort *Autoconnect Script-Datei für Inbox NVMe over FC Drivers* ein und wählen Sie die neueste Version für Ihr Betriebssystem.
.. Ändern Sie für Qlogic `/lib/systemd/system/nvmefc-boot-connections.service` Nach der Installation des Broadcom NVMe/FC-Skripts für die automatische Anbindung Folgendes enthält:
+
[listing]
----
[Unit]
Description=Auto-connect to subsystems on FC-NVME devices found during boot

[Service]
Type=oneshot
ExecStart=/bin/sh -c "echo add > /sys/class/fc/fc_udev_device/nvme_discovery"

[Install]
WantedBy=default.target
----


. Aktivieren und starten Sie den `nvmefc-boot-connections` Service:
+
[listing]
----
systemctl enable nvmefc-boot-connections.service
----
+
[listing]
----
systemctl start nvmefc-boot-connections.service
----


*Host-seitiges Setup für Emulex HBAs:*


NOTE: Folgende Schritte gelten nur für Emulex HBAs.

. Einstellen `lpfc_enable_fc4_type` Bis `3` Aktivieren von SLES12 SP4 als NVMe/FC-Initiator.
+
[listing]
----
# cat /etc/modprobe.d/lpfc.conf
options lpfc lpfc_enable_fc4_type=3
----
. Bauen Sie die neu auf `initrd` Um die Änderung der Emulex- und der Boot-Parameter zu erhalten.
+
[listing]
----
# dracut --force
----
. Starten Sie den Host neu, um die Änderungen auf zu laden `Ipfc` Treiber.
+
[listing]
----
# reboot
----
+
Der Host wird neu gestartet und der NVMe/FC-Initiator ist auf dem Host aktiviert.

+

NOTE: Nach dem Abschluss der Host-seitigen Einrichtung werden die NVMe over Fibre Channel-Ports automatisch verbunden.


