---
permalink: config-linux/nvme-ib-set-up-failover-task.html 
sidebar: sidebar 
keywords: failover, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Konfigurieren Sie den Host für das Failover. 
---
= Failover auf dem Host in E-Series einrichten – Linux (NVMe over InfiniBand)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um einen redundanten Pfad zum Speicher-Array bereitzustellen, können Sie den Host so konfigurieren, dass ein Failover ausgeführt wird.

.Bevor Sie beginnen
Sie müssen die erforderlichen Pakete auf Ihrem System installieren.

* Überprüfen Sie für Red hat-Hosts (RHEL), ob die Pakete durch Ausführen installiert wurden `rpm -q device-mapper-multipath`
* Überprüfen Sie bei SLES-Hosts, ob die Pakete durch Ausführen installiert wurden `rpm -q multipath-tools`
+

NOTE: Siehe  https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^] Um sicherzustellen, dass erforderliche Updates installiert werden, da Multipathing möglicherweise nicht korrekt mit den GA-Versionen von SLES oder RHEL funktioniert.



 SLES 12 use Device Mapper Multipath (DMMP) for multipathing when using NVMe over Infiniband. RHEL 8, RHEL 9, RHEL 10, SLES 15 and SLES 16 use a built-in Native NVMe Failover. Depending on which OS you are running, some additional configuration of multipath is required to get it running properly.


[[enable-device-mapper-multipath-dmmp-sles-12]]
== Aktivieren von Device Mapper Multipath (DMMP) SLES 12

Standardmäßig ist DM-MP in SLES deaktiviert. Führen Sie die folgenden Schritte aus, um DM-MP-Komponenten auf dem Host zu aktivieren.

.Schritte
. Fügen Sie den NVMe E-Series Geräteeintrag dem Abschnitt Geräte der Datei /etc/Multipath.conf ein, wie im folgenden Beispiel dargestellt:
+
[listing]
----

devices {
        device {
                vendor "NVME"
                product "NetApp E-Series*"
                path_grouping_policy group_by_prio
                failback immediate
                no_path_retry 30
        }
}
----
. Konfigurieren `multipathd` Zum Starten beim Systemstart.
+
[listing]
----
# systemctl enable multipathd
----
. Starten `multipathd` Wenn er derzeit nicht ausgeführt wird.
+
[listing]
----
# systemctl start multipathd
----
. Überprüfen Sie den Status von `multipathd` Um sicherzustellen, dass es aktiv ist und ausgeführt wird:
+
[listing]
----
# systemctl status multipathd
----




[[setting-up-rhel-8-with-native-nvme-multipathing]]
== Einrichtung von RHEL 8 mit nativem NVMe-Multipathing

Natives NVMe-Multipathing ist in RHEL 8 standardmäßig deaktiviert und muss mit den folgenden Schritten aktiviert werden.

. Einrichtung `modprobe` Regel zur Aktivierung von nativem NVMe-Multipathing.
+
[listing]
----
# echo "options nvme_core multipath=y" >> /etc/modprobe.d/50-nvme_core.conf
----
. Remake `initramfs` Mit neu `modprobe` Parameter.
+
[listing]
----
# dracut -f
----
. Starten Sie den Server neu, um ihn mit aktiviertem nativen NVMe-Multipathing zu aktivieren.
+
[listing]
----
# reboot
----
. Überprüfen Sie, ob natives NVMe-Multipathing aktiviert wurde, nachdem der Host den Backup gestartet hat.
+
[listing]
----
# cat /sys/module/nvme_core/parameters/multipath
----
+
.. Wenn die Befehlsausgabe lautet `N`, Dann ist natives NVMe-Multipathing noch deaktiviert.
.. Wenn die Befehlsausgabe lautet `Y`, Natives NVMe-Multipathing ist dann aktiviert und alle entdeckten NVMe-Geräte werden es nutzen.





NOTE: Bei SLES 15 und RHEL 9 ist nativem NVMe Multipathing standardmäßig aktiviert, und es ist keine zusätzliche Konfiguration erforderlich.



[[configure-nvme-io-policy]]
== Konfiguration der NVMe E/A-Richtlinie

.Über diese Aufgabe
Linux NVMe nativ für Multipathing verwendet möglicherweise standardmäßig die  `numa`I/O-Richtlinie. Für E-Series/EF-Series NVMe-over-Fabrics Konfigurationen ist die empfohlene I/O-Richtlinie  `round-robin`, die E/A gleichmäßig auf alle verfügbaren Pfade verteilt.

.Schritte
. Die aktuelle NVMe-E/A-Richtlinie wird überprüft:
+
[listing]
----
# cat /sys/module/nvme_core/parameters/iopolicy
numa
----
. Die  `round-robin`E/A-Richtlinie kann mit einer der folgenden Methoden festgelegt werden:
+
** *Persistent (empfohlen)*: Es wird eine udev-Regeldatei erstellt.
+
.<code>/etc/udev/rules.d/71-nvme-io-policy.rules</code>
[listing]
----
ACTION=="add|change", SUBSYSTEM=="nvme-subsystem", ATTR{iopolicy}="round-robin"
----
+
Anschließend die Regeln neu laden und anwenden:

+
[listing]
----
udevadm control --reload
udevadm trigger --subsystem-match=nvme-subsystem
----
** *Globale Einstellung beim Systemstart* - Der folgende Kernel-Parameter ist Ihrer Bootloader-Konfiguration hinzuzufügen:
+
[listing]
----
nvme_core.iopolicy=round-robin
----
** *Nicht persistent (online, keine E/A-Unterbrechung)* - sofortige Anwendung ohne Neustart:
+
[listing]
----
echo "round-robin" > /sys/class/nvme-subsystem/nvme-subsys0/iopolicy
----
+

NOTE: Diese Einstellung bleibt nach einem Neustart nicht erhalten.




