---
permalink: config-linux/nvme-roce-setup-host-side-task.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Die NVMe-Initiatorkonfiguration in einer RoCE-Umgebung umfasst die Installation und Konfiguration von rdma-Core- und nvme-cli-Paketen, die Konfiguration von Initiator-IP-Adressen und das Einrichten der NVMe-of-Schicht auf dem Host. 
---
= NVMe-Initiator über RoCE auf dem Host in der E-Series - Linux einrichten
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die NVMe-Initiatorkonfiguration in einer RoCE-Umgebung umfasst die Installation und Konfiguration von rdma-Core- und nvme-cli-Paketen, die Konfiguration von Initiator-IP-Adressen und das Einrichten der NVMe-of-Schicht auf dem Host.

.Bevor Sie beginnen
Sie müssen das neueste kompatible Betriebssystem RHEL 9, RHEL 10, SLES 15 oder SLES 16 mit Service Pack ausführen. Siehe die https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^] für eine vollständige Liste der aktuellen Anforderungen.

.Schritte
. rdma- und nvme-cli-Pakete installieren:
+
*SLES 15 oder SLES 16*

+
[listing]
----

# zypper install rdma-core
# zypper install nvme-cli
----
+
*RHEL 9 und RHEL 10*

+
[listing]
----

# yum install rdma-core
# yum install nvme-cli
----



NOTE: Wenn Sie eine NVIDIA HCA verwenden und den externen DOCA-Treiber nutzen möchten, lesen Sie bitte die link:https://developer.nvidia.com/doca-downloads["NVIDIA DOCA-Dokumentation"] für Informationen zur korrekten Installation in dieser Umgebung.

. Für RHEL 9 Netzwerk-Skripte installieren:
+
*RHEL 9*

+
[listing]
----
# yum install NetworkManager-initscripts-updown
----
+

NOTE: Netzwerkskripte sind für RHEL 10 nicht verfügbar.

. Holen Sie den Host-NQN ab, mit dem der Host für ein Array konfiguriert werden kann.
+
[listing]
----
# cat /etc/nvme/hostnqn
----
. Richten Sie IPv4-IP-Adressen auf den ethernet-Ports ein, die für die Verbindung von NVMe over RoCE verwendet werden. Erstellen Sie für jede Netzwerkschnittstelle ein Konfigurationsskript, das die verschiedenen Variablen für diese Schnittstelle enthält.
+
Die in diesem Schritt verwendeten Variablen basieren auf der Server-Hardware und der Netzwerkumgebung. Die Variablen enthalten die `IPADDR` Und `GATEWAY`. Dies sind Beispielanweisungen für SLES und RHEL:

+
*SLES 15*

+
Erstellen Sie die Beispieldatei `/etc/sysconfig/network/ifcfg-eth4` mit folgendem Inhalt, wobei MTU auf den höchsten Wert eingestellt ist, der ohne Paketfragmentierung erreicht werden kann (normalerweise 9000).

+
[listing]
----
BOOTPROTO='static'
BROADCAST=
ETHTOOL_OPTIONS=
IPADDR='192.168.1.87/24'
GATEWAY='192.168.1.1'
MTU=9000
NAME='MT27800 Family [ConnectX-5]'
NETWORK=
REMOTE_IPADDR=
STARTMODE='auto'
----
+
Erstellen Sie dann die Beispieldatei `/etc/sysconfig/network/ifcfg-eth5`:

+
[listing]
----
BOOTPROTO='static'
BROADCAST=
ETHTOOL_OPTIONS=
IPADDR='192.168.2.87/24'
GATEWAY='192.168.2.1'
MTU=9000
NAME='MT27800 Family [ConnectX-5]'
NETWORK=
REMOTE_IPADDR=
STARTMODE='auto'
----
+
*RHEL 9, RHEL 10 oder SLES 16*

+
Verwenden Sie die `nmtui` Werkzeug zum Aktivieren und Bearbeiten einer Verbindung. Unten sehen Sie eine Beispieldatei `/etc/NetworkManager/system-connections/eth4.nmconnection` Das Tool generiert Folgendes:

+
[listing]
----

[connection]
id=eth4
uuid=<unique uuid>
type=ethernet
interface-name=eth4

[ethernet]
mtu=9000

[ipv4]
address1=192.168.1.87/24
method=manual

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
----
+
Unten sehen Sie eine Beispieldatei `/etc/NetworkManager/system-connections/eth5.nmconnection` Das Tool generiert Folgendes:

+
[listing]
----

[connection]
id=eth5
uuid=<unique uuid>
type=ethernet
interface-name=eth5

[ethernet]
mtu=9000

[ipv4]
address1=192.168.2.87/24
method=manual

[ipv6]
addr-gen-mode=default
method=auto

[proxy]
----
. Aktivieren der Netzwerkschnittstellen:
+
[listing]
----

# nmcli connection up eth4
# nmcli connection up eth5
----
. Legen Sie auf dem Host den NVMe-of-Layer fest. Erstellen Sie die folgende Datei unter `/etc/modules-load.d/` Um die zu laden `nvme_rdma` Kernel-Modul und stellen Sie sicher, dass das Kernel-Modul immer eingeschaltet ist, auch nach einem Neustart:
+
[listing]
----

# cat /etc/modules-load.d/nvme_rdma.conf
  nvme_rdma
----
. Starten Sie den Host neu.
+
.. Alternativ können Sie den  `nvme_rdma`Kernel auch ohne Neustart laden, indem Sie diesen Befehl ausführen:
+
[listing]
----

# modeprobe nvme_rdma
----


. Um zu überprüfen, ob das  `nvme_rdma` Kernelmodul geladen ist, führen Sie diesen Befehl aus:
+
[listing]
----
# lsmod | grep nvme
nvme_rdma              36864  0
nvme_fabrics           24576  1 nvme_rdma
nvme_core             114688  5 nvme_rdma,nvme_fabrics
rdma_cm               114688  7 rpcrdma,ib_srpt,ib_srp,nvme_rdma,ib_iser,ib_isert,rdma_ucm
ib_core               393216  15 rdma_cm,ib_ipoib,rpcrdma,ib_srpt,ib_srp,nvme_rdma,iw_cm,ib_iser,ib_umad,ib_isert,rdma_ucm,ib_uverbs,mlx5_ib,qedr,ib_cm
t10_pi                 16384  2 sd_mod,nvme_core
----
+
.Was kommt als Nächstes?
Nachdem Sie den NVMe-Initiator über RoCE auf dem Host eingerichtet haben, link:nvme-roce-configure-storage-connections-task.html["Konfigurieren Sie die NVMe over RoCE-Porteinstellungen"].


