---
permalink: config-linux/overview-concept.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Prüfen Sie die Anforderungen für die Verwendung der Express-Methode zur Einrichtung eines E-Series-Arrays und eines Linux-Hosts. 
---
= Voraussetzungen
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Linux Express-Methode basiert auf folgenden Annahmen:

|===
| Komponente | Voraussetzungen 


 a| 
Trennt
 a| 
* Sie haben zur Installation der Hardware die in den Controller-Shelfs enthaltene Installations- und Setup-Anleitung verwendet.
* Sie haben Kabel zwischen den optionalen Laufwerk-Shelfs und den Controllern verbunden.
* Sie haben das Storage-System mit Strom versorgt.
* Sie haben alle anderen Hardware installiert (z. B. Management Station, Switches) und die notwendigen Verbindungen hergestellt.
* Wenn Sie NVMe over Infiniband, NVMe over RoCE oder NVMe over Fibre Channel verwenden, enthält jeder EF300-, EF600-, EF570- oder E5700-Controller mindestens 32 GB RAM.




 a| 
Host
 a| 
* Sie haben eine Verbindung zwischen dem Speichersystem und dem Daten-Host hergestellt.
* Sie haben das Host-Betriebssystem installiert.
* Sie nutzen Linux nicht als virtualisierten Gast.
* Sie konfigurieren den Host der Daten (I/O-Attached) nicht für den Booten über das SAN.
* Sie haben alle OS-Updates installiert, die unter aufgeführt sind https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].




 a| 
Storage Management Station
 a| 
* Sie verwenden ein 1-Gbit/s- oder schnelleres Managementnetzwerk.
* Sie verwenden für die Verwaltung eine separate Station statt des (I/O-angeschlossenen) Host.
* Sie verwenden ein Out-of-Band-Management, bei dem eine Storage-Management-Station Befehle über die Ethernet-Verbindungen zum Controller an das Storage-System sendet.
* Sie haben die Management-Station mit demselben Subnetz wie die Storage-Management-Ports verbunden.




 a| 
IP-Adresse
 a| 
* Sie haben einen DHCP-Server installiert und konfiguriert.
* Sie haben *noch nicht* eine Ethernet-Verbindung zwischen der Management Station und dem Speichersystem hergestellt.




 a| 
Storage-Bereitstellung
 a| 
* Freigegebene Volumes werden nicht verwendet.
* Sie erstellen Pools statt Volume-Gruppen.




 a| 
Protokoll FC
 a| 
* Sie haben alle Host-seitigen FC-Verbindungen und aktiviertes Switch-Zoning vorgenommen.
* Sie verwenden von NetApp unterstützte FC HBAs und Switches.
* Sie verwenden den FC-HBA-Treiber und die in aufgeführten Firmware-Versionen https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].




 a| 
Protokoll: ISCSI
 a| 
* Sie verwenden Ethernet-Switches, die iSCSI-Datenverkehr transportieren können.
* Sie haben die Ethernet-Switches gemäß der Empfehlung des Anbieters für iSCSI konfiguriert.




 a| 
Protokoll SAS
 a| 
* Sie verwenden von NetApp unterstützte SAS HBAs.
* Sie verwenden den SAS-HBA-Treiber und die in aufgeführten Firmware-Versionen https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].




 a| 
Protokoll: ISER über InfiniBand
 a| 
* Sie verwenden eine InfiniBand-Fabric.
* Sie verwenden den in aufgeführten IB-iSER-HBA-Treiber und die Firmware-Versionen https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].




 a| 
Protokoll: SRP über InfiniBand
 a| 
* Sie verwenden eine InfiniBand-Fabric.
* Sie verwenden IB-SRP-Treiber und Firmware-Versionen, wie in aufgeführt https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].




 a| 
Protokoll: NVMe over InfiniBand
 a| 
* Sie haben die 100-GB- oder 200-G-Host-Schnittstellenkarten in einem EF300-, EF600-, EF570- oder E5700-Storage-System erhalten, das mit dem NVMe-over-InfiniBand-Protokoll vorkonfiguriert ist, oder die Controller wurden mit Standard-IB-Ports bestellt und müssen in NVMe-of-Ports konvertiert werden.
* Sie verwenden eine InfiniBand-Fabric.
* Sie verwenden den in aufgeführten NVMe/IB-Treiber und die Firmware-Versionen https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].




 a| 
Protokoll: NVMe over RoCE
 a| 
* Sie haben die 100 g oder 200 G Host-Schnittstellenkarten in einem EF300-, EF600-, EF570- oder E5700-Storage-System erhalten, das mit dem NVMe-over-RoCE-Protokoll vorkonfiguriert ist, oder die Controller wurden mit Standard-IB-Ports bestellt und müssen in NVMe-of-Ports konvertiert werden.
* Die in aufgeführten NVMe/RoCE-Treiber und Firmware-Versionen werden verwendet https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].




 a| 
Protokoll: NVMe over Fibre Channel
 a| 
* Sie haben die 32-G-Host-Schnittstellenkarten in einem EF300-, EF600-, EF570- oder E5700 Storage-System erhalten, das mit dem NVMe-over-Fibre-Channel-Protokoll vorkonfiguriert ist, oder die Controller wurden mit Standard-FC-Ports bestellt und in NVMe-of-Ports konvertiert.
* Sie verwenden den in aufgeführten NVMe/FC-Treiber und Firmware-Versionen https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].


|===

NOTE: Diese Express-Anweisungen enthalten Beispiele für SUSE Linux Enterprise Server (SLES) und für Red hat Enterprise Linux (RHEL).
