---
permalink: config-linux/sas-determine-sas-host-ids-task.html 
sidebar: sidebar 
keywords: express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Sie suchen für das SAS-Protokoll die SAS-Adressen unter Verwendung des HBA-Dienstprogramms und verwenden das HBA-BIOS, um die entsprechenden Konfigurationseinstellungen vorzunehmen. 
---
= SAS-Host-IDs in der E-Series – Linux (SAS) ermitteln
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie suchen für das SAS-Protokoll die SAS-Adressen unter Verwendung des HBA-Dienstprogramms und verwenden das HBA-BIOS, um die entsprechenden Konfigurationseinstellungen vorzunehmen.

Lesen Sie die folgenden Richtlinien für HBA-Dienstprogramme, bevor Sie mit diesem Verfahren beginnen:

* Die meisten HBA-Anbieter bieten ein HBA-Dienstprogramm an. Verwenden Sie je nach Host-Betriebssystem und CPU entweder das LSI-sas2flash (6G) oder sas3flash (12G) Utility.


.Schritte
. Laden Sie das HBA-Dienstprogramm von der Website Ihres HBA-Anbieters herunter.
. Installieren Sie das Dienstprogramm.
. Verwenden Sie das HBA-BIOS, um die entsprechenden Einstellungen für Ihre Konfiguration auszuwählen.
+
Siehe die Spalte Notizen des https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^] Empfehlungen.


