---
permalink: config-linux/sas-install-configure-host-utilities-task.html 
sidebar: sidebar 
keywords: Linux Unified Host Utilities, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries, SMcli, SMdevices 
summary: Linux Unified Host Utilities 7.1 enthält Tools für das Management von NetApp Storage, einschließlich Failover-Richtlinien und physischen Pfaden. 
---
= Installation und Konfiguration von Linux Unified Host Utilities in E-Series (SAS)
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Linux Unified Host Utilities Tools unterstützen Sie beim Management von NetApp Storage, einschließlich Failover-Richtlinien und physischen Pfaden.

.Schritte
. Verwenden Sie die https://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^] Bestimmen der entsprechenden Version der zu installierenden Unified Host Utilities.
+
Die Versionen werden in jeder unterstützten Konfiguration in einer Spalte aufgelistet.

. Laden Sie die Unified Host Utilities von herunter https://mysupport.netapp.com/site/["NetApp Support"^].
+

NOTE: Alternativ können Sie den SMcli-Befehl verwenden `-identifyDevices` Um dieselben Funktionen wie das Unified Host Utility-Tool auszuführen. Die SMcli ist im SANtricity Betriebssystem enthalten und kann über den SANtricity System Manager heruntergeladen werden. Weitere Informationen zum Herunterladen des SMcli über den SANtricity-System-Manager finden Sie im https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html["Laden Sie das Thema Befehlszeilenschnittstelle (CLI) in der Online-Hilfe des SANtricity Systemmanagers herunter"^].


