---
permalink: config-linux/srp-ib-install-smcli-11-53-task.html 
sidebar: sidebar 
keywords: Storage Manager, cli, command line interface, express linux configuration, software configuration, linux host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: 'Wenn Sie die SANtricity Storage Manager-Software auf Ihrer Management Station installieren, werden standardmäßig eine grafische Benutzeroberfläche \(GUI\) und eine Befehlszeilenschnittstelle \(CLI\) installiert. Bei diesen Anweisungen wird davon ausgegangen, dass Sie die SANtricity-Speicher-Manager-GUI auf einer Management-Station und nicht auf dem I/O-Host installieren.' 
---
= SANtricity Storage Manager für SMcli installieren (11.53 oder früher) – Linux (SRP über InfiniBand)
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Sie die SANtricity-Software 11.53 oder eine frühere Version verwenden, können Sie die SANtricity Storage Manager-Software auf Ihrer Management Station installieren, um das Array zu verwalten.

SANtricity Storage Manager enthält die Befehlszeilenschnittstelle (CLI) für weitere Managementaufgaben und den Host Context Agent, damit die Host-Konfigurationsinformationen über den I/O-Pfad an die Storage Array Controller übertragen werden können.


NOTE: Wenn Sie SANtricity Software 11.60 und höher verwenden, müssen Sie diese Schritte nicht ausführen. Die sichere SANtricity CLI (SMcli) ist im SANtricity Betriebssystem enthalten und kann über den SANtricity System Manager heruntergeladen werden. Weitere Informationen zum Herunterladen des SMcli über den SANtricity-System-Manager finden Sie im link:https://docs.netapp.com/us-en/e-series-santricity/sm-settings/download-cli.html["Laden Sie das Thema Befehlszeilenschnittstelle (CLI) in der Online-Hilfe des SANtricity Systemmanagers herunter"^]


NOTE: Ab der SANtricity-Softwareversion 11.80.1 wird der Host Context Agent nicht mehr unterstützt.

.Bevor Sie beginnen
Stellen Sie sicher, dass Sie Folgendes haben:

* SANtricity Software 11.53 oder früher.
* Korrigieren Sie Administrator- oder Superuser-Berechtigungen.
* Ein System für den SANtricity Storage Manager Client mit den folgenden Mindestanforderungen:
+
** *RAM*: 2 GB für Java Runtime Engine
** *Speicherplatz*: 5 GB
** *OS/Architektur*: Informationen zur Bestimmung der unterstützten Betriebssystemversionen und Architekturen finden Sie unter http://mysupport.netapp.com["NetApp Support"^]. Klicken Sie auf der Registerkarte *Downloads* auf Menü:Downloads[SANtricity Storage Manager der E-Serie].




.Über diese Aufgabe
In dieser Aufgabe wird beschrieben, wie SANtricity Storage Manager sowohl auf Windows- als auch auf Linux-Betriebssystemplattformen installiert wird, da sowohl Windows als auch Linux gemeinsame Management-Station-Plattformen sind, wenn Linux für den Daten-Host verwendet wird.

.Schritte
. Laden Sie die Softwareversion von SANtricity unter herunter http://mysupport.netapp.com["NetApp Support"^]. Klicken Sie auf der Registerkarte *Downloads* auf Menü:Downloads[SANtricity Storage Manager der E-Serie].
. Führen Sie das SANtricity-Installationsprogramm aus.
+
|===
| Windows | Linux 


 a| 
Doppelklicken Sie auf das Installationspaket SMIA*.exe, um die Installation zu starten.
 a| 
.. Gehen Sie in das Verzeichnis, in dem sich das SMIA*.bin Installationspaket befindet.
.. Wenn der Temp-Mount-Punkt nicht über Berechtigungen zum Ausführen verfügt, stellen Sie das ein `IATEMPDIR` Variabel. Beispiel: `IATEMPDIR=/root ./SMIA-LINUXX64-11.25.0A00.0002.bin`
.. Führen Sie die aus `chmod +x SMIA*.bin` Befehl, um der Datei die Berechtigung Ausführen zu erteilen.
.. Führen Sie die aus `./SMIA*.bin` Befehl zum Starten des Installationsprogramms.


|===
. Verwenden Sie den Installationsassistenten, um die Software auf der Management Station zu installieren.

