---
permalink: maintenance-e2800/hics-overview-supertask-concept.html 
sidebar: sidebar 
keywords: E2800 replace HIC, E2800 replace host interface card, replacing E2800 HIC, E2800 replace HIC, adding E2800 HIC, upgrading E2800 HIC, E2800, E-Series, eseries 
summary: Anforderungen für den Austausch der E2800 HIC prüfen 
---
= Anforderungen für den Austausch der E2800 HIC
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prüfen Sie die Anforderungen und Überlegungen, bevor Sie eine Host-Schnittstellenkarte (HIC) in einer E2800 hinzufügen, aktualisieren oder ersetzen.



== Verfahrensübersicht

Die Schritte zum Ersetzen einer HIC hängen davon ab, ob Sie einen oder zwei Controller haben:

|===
| Wenn Ihr Storage Array... | Sie müssen... 


 a| 
Ein Controller (E2812 oder E2824 Simplexkonfiguration)
 a| 
. Stoppen Sie Host-I/O-Vorgänge
. Schalten Sie das Controller-Shelf aus
. Den Controller-Behälter ausbauen
. Tauschen Sie die Batterie aus
. Den Controller-Behälter austauschen
. Schalten Sie das Controller-Shelf ein




 a| 
Zwei Controller (E2860, E2812 oder E2824-Duplex)
 a| 
. Versetzen Sie den Controller in den Offline-Modus
. Den Controller-Behälter ausbauen
. Tauschen Sie die Batterie aus
. Den Controller-Behälter austauschen
. Versetzen Sie den Controller in den Online-Modus


|===


== Anforderungen für das Hinzufügen, Aktualisieren oder Ersetzen einer HIC

Wenn Sie eine Host Interface Card (HIC) hinzufügen, aktualisieren oder ersetzen möchten, beachten Sie bitte die folgenden Anforderungen.

* Sie haben für dieses Verfahren ein Zeitfenster für die Wartung von Ausfallzeiten eingeplant. Die Stromversorgung muss ausgeschaltet sein, wenn Sie HICs installieren. Daher können Sie erst dann auf Daten im Speicher-Array zugreifen, wenn Sie diesen Vorgang erfolgreich abgeschlossen haben. (In einer Duplexkonfiguration liegt dies daran, dass beide Controller beim Einschalten dieselbe HIC-Konfiguration haben müssen.)
* Es gibt ein oder zwei HICs, je nachdem, ob Sie über einen oder zwei Controller in Ihrem Storage-Array verfügen. Die HICs müssen mit Ihren Steuerungen kompatibel sein.
+
Bei einer Duplexkonfiguration (zwei Controller) müssen die HICs, die in den beiden Controller-Kanistern installiert sind, identisch sein. Wenn nicht übereinstimmende HIC vorhanden sind, wird der Controller mit der Ersatz-HIC gesperrt, wenn Sie ihn online schalten.

* Für die Verbindung der neuen Host-Ports sind alle Kabel, Transceiver, Switches und Host Bus Adapter (HBAs) erforderlich.
+
Informationen über kompatible Hardware finden Sie im https://mysupport.netapp.com/NOW/products/interoperability["NetApp Interoperabilitätsmatrix"^] Oder im http://hwu.netapp.com/home.aspx["NetApp Hardware Universe"^].

* Sie haben ein ESD-Armband oder andere antistatische Vorsichtsmaßnahmen getroffen.
* Sie haben einen #1 Kreuzschlitzschraubendreher.
* Sie haben Etiketten, um jedes Kabel zu identifizieren, das mit dem Controller-Behälter verbunden ist.
* Sie verfügen über eine Management Station mit einem Browser, der für den Controller auf den SANtricity System Manager zugreifen kann. (Zeigen Sie zum Öffnen der System Manager-Schnittstelle den Domain-Namen oder die IP-Adresse des Controllers im Browser.)

