---
sidebar: sidebar 
permalink: manage-storage.html 
keywords: online help, System Manager, Unified Manager 
summary: Storage-Management 
---
= Storage-Management
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Über die nachfolgenden Links gelangen Sie zu Dokumentation, in der Sie beschreibt, wie Storage-Objekte und E-Series Storage-Systeme konfiguriert, gemanagt und überwacht werden. Die Links führen Sie zu einer anderen Dokumentationswebsite.



== Online-Hilfe für System Manager

Greifen Sie auf die https://docs.netapp.com/us-en/e-series-santricity/system-manager/index.html["Die Online-Hilfe von SANtricity System Manager"^] zu, wo Sie Informationen zur Planung, Konfiguration, Verwaltung und Fehlerbehebung Ihres Speicher-Arrays finden können.



== Online-Hilfe für Unified Manager

Greifen Sie auf die https://docs.netapp.com/us-en/e-series-santricity/unified-manager/index.html["Online-Hilfe von SANtricity Unified Manager"^] zu, wo Sie lernen können, wie Sie Storage-Management-Befehle auf mehreren Netzwerk-Speicher-Arrays ausführen.



== Befehlsreferenz

Auf das zugreifen https://docs.netapp.com/us-en/e-series-cli/index.html["Befehlsreferenz"^], Wo Sie lernen, wie Sie Ihre Speicher-Arrays mit Hilfe von CLI-Befehlen (Command Line Interface) konfigurieren und überwachen können.
