---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.73 
summary: Neue Funktionen im SANtricity OS. 
---
= Was ist neu in SANtricity OS
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In der folgenden Tabelle werden die neuen Funktionen von SANtricity OS 11.8 für integriertes Management der EF300, EF600, E2800/EF280 und E5700/EF570 Controller beschrieben.



== Neue Funktionen in Version 11.80

[cols="35h,~"]
|===
| Neues Feature | Beschreibung 


 a| 
Verbesserter Volume Parity Scan
 a| 
Der Volume-Paritäts-Scan kann nun als Hintergrundprozess entweder über die REST API oder über die CLI gestartet werden. Der daraus resultierende Paritäts-Scan wird im Hintergrund ausgeführt, solange er für den Abschluss des Scanvorgangs erforderlich ist. Scanvorgänge können den Neustart des Controllers und Failover-Vorgänge überdauern.



 a| 
SAML-Unterstützung für Unified Manager
 a| 
Unified Manager unterstützt jetzt SAML (Security Assertion Markup Language). Sobald SAML für Unified Manager aktiviert ist, müssen Benutzer eine Multi-Faktor-Authentifizierung für den Identitätsanbieter verwenden, um mit der Benutzeroberfläche zu interagieren. Beachten Sie, dass die REST-API nach der Aktivierung von SAML in Unified Manager nicht verwendet werden kann, ohne über das IdP zu gehen, um Anfragen zu authentifizieren.



 a| 
Automatische Konfigurationsfunktion
 a| 
Unterstützt jetzt die Möglichkeit, den Parameter für die Blockgröße des Volumens für die Verwendung mit der Funktion „Automatische Konfiguration“ für die Ersteinrichtung des Arrays festzulegen. Diese Funktion ist in der CLI nur als „blocksize“ Parameter verfügbar.



 a| 
Kryptografische Signierung Der Controller-Firmware
 a| 
Die Controller-Firmware ist kryptografisch signiert. Die Signaturen werden beim ersten Download und beim Booten des Controllers überprüft. Keine Auswirkungen für Endbenutzer zu erwarten. Signaturen werden durch ein von der Zertifizierungsstelle ausgestelltes Extended Validation-Zertifikat gesichert.



 a| 
Kryptografische Signierung Der Laufwerksfirmware
 a| 
Die Festplatten-Firmware ist kryptografisch signiert. Die Signaturen werden beim ersten Download überprüft und durch ein von der Zertifizierungsstelle ausgestelltes Extended Validation-Zertifikat gesichert. Der Inhalt der Laufwerksfirmware wird nun als ZIP-Datei geliefert, die sowohl die ältere, nicht signierte Firmware als auch die neu signierte Firmware enthält. Der Benutzer muss die entsprechende Datei basierend auf der Versionsversion des Codes auswählen, der auf dem Zielsystem ausgeführt wird.



 a| 
Externe Schlüsselserver-Verwaltung - Zertifikatschlüsselgröße
 a| 
Die neue Standardgröße des Zertifikatschlüssels beträgt 3072 Bit (ab 2048). Schlüsselgrößen bis zu 4096 Bit werden unterstützt. Ein NVSRAM-Bit muss geändert werden, um die nicht standardmäßigen Schlüsselgrößen zu unterstützen.



 a| 
Unterstützung für größere dynamische Festplatten-Pools mit Laufwerken mit 512 b Blockgrößen
 a| 
Kunden, die den Versionstyp des Pools der Version 1 verwenden, können nun einen Disk-Pool mit einer maximalen Größe von 48 TB haben. Die ältere Version unterstützt bis zu 24 TB Disk Pool Größe. Wenn vorhandene Festplatten-Pools in eine größere Größe umgewandelt werden sollen, müssen zuerst alle Volumes entfernt werden. Ein Downgrade-Vorgang ist eingeschränkt, wenn ein Laufwerkspool der Version 1 vorhanden ist.



 a| 
System Manager und Unified Manager werden nur gestartet, wenn die Mindestanforderungen des Browsers erfüllt sind
 a| 
Bevor System Manager oder Unified Manager gestartet wird, ist eine Mindestversion des Browsers erforderlich. Folgende Versionen werden mindestens unterstützt:

* Firefox Mindestversion 80
* Chrome Mindestversion 89
* Edge Mindestversion 90
* Safari Mindestversion 14




 a| 
Unterstützung für FIPS 140-3 NVMe-SSD-Laufwerke
 a| 
NetApp-zertifizierte NVMe-SSD-Laufwerke nach FIPS 140-3 werden jetzt unterstützt. Diese werden im Speicher-Array-Profil und im System Manager korrekt identifiziert.



 a| 
Unterstützung für SSD-Lese-Cache auf EF300 und EF600
 a| 
SSD-Lese-Cache wird jetzt auf EF300- und EF600-Controllern unterstützt, die HDD mit SAS-Erweiterung verwenden.



 a| 
Unterstützung für asynchrone Remote-Spiegelung von iSCSI und Fibre Channel auf EF300 und EF600
 a| 
Asynchrone Remote-Spiegelung (ARVM) wird nun auf EF300- und EF600-Controllern mit NVMe und SAS-basierten Volumes unterstützt.



 a| 
Unterstützung für EF300 und EF600 ohne Laufwerke im Basifach
 a| 
EF300- und EF600-Controller-Konfigurationen ohne NVMe-Laufwerke in der Basis-Tray werden jetzt unterstützt.



 a| 
USB-Anschlüsse für alle Plattformen deaktiviert
 a| 
USB-Anschlüsse sind jetzt auf allen Plattformen deaktiviert.

|===