---
sidebar: sidebar 
permalink: whats-new.html 
keywords: whats new, new features, SANtricity 11.73 
summary: Neue Funktionen im SANtricity OS. 
---
= Was ist neu in SANtricity OS
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
In der folgenden Tabelle werden die neuen Funktionen von SANtricity OS 11.8 für integriertes Management der EF300, EF600, E2800/EF280 und E5700/EF570 Controller beschrieben.



== Neue Funktionen in Version 11.80

[cols="35h,~"]
|===
| Neues Feature | Beschreibung 


 a| 
Verbesserter Volume Parity Scan
 a| 
Der Volume-Paritäts-Scan kann nun als Hintergrundprozess entweder über die REST API oder über die CLI gestartet werden. Der daraus resultierende Paritäts-Scan wird im Hintergrund ausgeführt, solange er für den Abschluss des Scanvorgangs erforderlich ist. Scanvorgänge können den Neustart des Controllers und Failover-Vorgänge überdauern.



 a| 
SAML-Unterstützung für Unified Manager
 a| 
Unified Manager unterstützt jetzt SAML (Security Assertion Markup Language). Sobald SAML für Unified Manager aktiviert ist, müssen Benutzer eine Multi-Faktor-Authentifizierung für den Identitätsanbieter verwenden, um mit der Benutzeroberfläche zu interagieren. Beachten Sie, dass die REST-API nach der Aktivierung von SAML in Unified Manager nicht verwendet werden kann, ohne über das IdP zu gehen, um Anfragen zu authentifizieren.



 a| 
Automatische Konfigurationsfunktion
 a| 
Unterstützt jetzt die Möglichkeit, den Parameter für die Blockgröße des Volumens für die Verwendung mit der Funktion „Automatische Konfiguration“ für die Ersteinrichtung des Arrays festzulegen. Diese Funktion ist in der CLI nur als „blocksize“ Parameter verfügbar.



 a| 
Kryptografische Signierung Der Controller-Firmware
 a| 
Die Controller-Firmware ist kryptografisch signiert. Die Signaturen werden beim ersten Download und beim Booten des Controllers überprüft. Keine Auswirkungen für Endbenutzer zu erwarten. Signaturen werden durch ein von der Zertifizierungsstelle ausgestelltes Extended Validation-Zertifikat gesichert.



 a| 
Kryptografische Signierung Der Laufwerksfirmware
 a| 
Die Festplatten-Firmware ist kryptografisch signiert. Die Signaturen werden beim ersten Download überprüft und durch ein von der Zertifizierungsstelle ausgestelltes Extended Validation-Zertifikat gesichert. Der Inhalt der Laufwerksfirmware wird nun als ZIP-Datei geliefert, die sowohl die ältere, nicht signierte Firmware als auch die neu signierte Firmware enthält. Der Benutzer muss die entsprechende Datei basierend auf der Versionsversion des Codes auswählen, der auf dem Zielsystem ausgeführt wird.



 a| 
Externe Schlüsselserver-Verwaltung - Zertifikatschlüsselgröße
 a| 
Die neue Standardgröße des Zertifikatschlüssels beträgt 3072 Bit (ab 2048). Schlüsselgrößen bis zu 4096 Bit werden unterstützt. Ein NVSRAM-Bit muss geändert werden, um die nicht standardmäßigen Schlüsselgrößen zu unterstützen.

Die Auswahlwerte für die Schlüsselgröße lauten wie folgt:

* STANDARD = 0
* LÄNGE 2048 = 1
* LÄNGE 3072 = 2
* LÄNGE 4096 = 3


So ändern Sie die Schlüsselgröße über SMcli auf 4096:

`set controller[b] globalnvsrambyte[0xc0]=3;`
`set controller[a] globalnvsrambyte[0xc0]=3;`

Schlüsselgröße abfragen:

`show allcontrollers globalnvsrambyte[0xc0];`



 a| 
Verbesserungen Am Laufwerk-Pool
 a| 
Festplatten-Pools, die mit Controllern erstellt werden, die 11.80 oder höher ausführen, sind _Version 1_ Pools im Gegensatz zu _Version 0_ Pools. Ein Downgrade-Vorgang ist eingeschränkt, wenn ein _Version 1_-Laufwerk-Pool vorhanden ist.

Die Version eines Laufwerkspools kann im Speicher-Array-Profil identifiziert werden.



 a| 
System Manager und Unified Manager werden nur gestartet, wenn die Mindestanforderungen des Browsers erfüllt sind
 a| 
Bevor System Manager oder Unified Manager gestartet wird, ist eine Mindestversion des Browsers erforderlich.

Folgende Versionen werden mindestens unterstützt:

* Firefox Mindestversion 80
* Chrome Mindestversion 89
* Edge Mindestversion 90
* Safari Mindestversion 14




 a| 
Unterstützung für FIPS 140-3 NVMe-SSD-Laufwerke
 a| 
NetApp-zertifizierte NVMe-SSD-Laufwerke nach FIPS 140-3 werden jetzt unterstützt. Diese werden im Speicher-Array-Profil und im System Manager korrekt identifiziert.



 a| 
Unterstützung für SSD-Lese-Cache auf EF300 und EF600
 a| 
SSD-Lese-Cache wird jetzt auf EF300- und EF600-Controllern unterstützt, die HDD mit SAS-Erweiterung verwenden.



 a| 
Unterstützung für asynchrone Remote-Spiegelung von iSCSI und Fibre Channel auf EF300 und EF600
 a| 
Asynchrone Remote-Spiegelung (ARVM) wird nun auf EF300- und EF600-Controllern mit NVMe und SAS-basierten Volumes unterstützt.



 a| 
Unterstützung für EF300 und EF600 ohne Laufwerke im Basifach
 a| 
EF300- und EF600-Controller-Konfigurationen ohne NVMe-Laufwerke in der Basis-Tray werden jetzt unterstützt.



 a| 
USB-Anschlüsse für alle Plattformen deaktiviert
 a| 
USB-Anschlüsse sind jetzt auf allen Plattformen deaktiviert.



 a| 
Höherer maximaler SSD-Lese-Cache
 a| 
Der maximale SSD-Lese-Cache wurde von 5 TB auf 8 TB erhöht.



 a| 
Weisen Sie in Duplexkonfigurationen einem einzelnen Volume All-Flash-Lese-Cache zu
 a| 
Der gesamte SSD-Lese-Cache kann nun auf Duplexsystemen demselben Volume zugewiesen werden, wenn ein einzelnes Volume den gesamten SSD-Cache nutzt.



 a| 
Die Laufwerkseriennummer wurde der Laufwerkzusammenfassungstabelle des Speicherarrayprofils hinzugefügt
 a| 
Die Seriennummer des Laufwerks wurde der Laufwerkzusammenfassungstabelle im Speicher-Array-Profil hinzugefügt.



 a| 
Dom0-misc-Logs wurden täglichen ASUP hinzugefügt
 a| 
Die dom0-misc-Protokolle für Controller A und B wurden den täglichen ASUPs hinzugefügt.



 a| 
Port 443 wird jetzt standardmäßig für die Kommunikation von Anwendungen mit eingebetteten Webdiensten verwendet
 a| 
Port 443 wird jetzt standardmäßig für die Kommunikation mit dem eingebetteten Webserver verwendet. Der  `-useLegacyTransferPort` Es wurde ein CLI-Befehl für diejenigen hinzugefügt, die stattdessen den Legacy 8443 Transfer Port verwenden möchten. Weitere Informationen zum neuen CLI-Befehl -useLegacyTransferPort finden Sie im https://docs.netapp.com/us-en/e-series-cli/whats-new.html["SANtricity CLI Neuheiten"].



 a| 
Scan-Volume-Parity Progress-Funktion
 a| 
Die folgenden CLI-Befehle wurden implementiert, um Job-basierte Volume Parity-Scan-Vorgänge zu unterstützen:

* Starten Sie die Prüfung der Volume-Parität
* Fehler beim Speichern der Volume-Paritätsprüfung
* Stoppen Sie die Überprüfung des Volume Parity Jobs
* Zeigt die Option „Check Volume Parity Job“ oder „Jobs“ an


Weitere Informationen zu den CLI-Befehlen des neuen Job-basierten Volume Parity Scan finden Sie im https://docs.netapp.com/us-en/e-series-cli/whats-new.html["SANtricity CLI Neuheiten"].



 a| 
MFA-Unterstützung für Unified Manager
 a| 
Multi-Faktor-Authentifizierung (MFA) wird jetzt unter Unified Manager unterstützt.



 a| 
Umschaltsymbol für die Hardware-Ansicht auf der Vorderseite
 a| 
In der Hardwareansicht von System Manager/Unified Manager stehen jetzt die folgenden beiden Registerkarten zur Steuerung der Vorder- und Rückansicht zur Verfügung:

* Registerkarte Laufwerke
* Registerkarte Controller & Komponenten




 a| 
VCenter Storage Plug-in
 a| 
Das vCenter Storage Plug-in wurde hinsichtlich der Kompatibilität mit der Version 11.80 der E-Series aktualisiert.



 a| 
Web Services Proxy 6.0
 a| 
Der Web Services Proxy wurde auf Version 6.0 aktualisiert, um die Kompatibilität mit der E-Series Version 11.80 zu gewährleisten.



 a| 
ASUP-Fallerstellungs-Flag für Ereignisse mit nominaler und maximaler Temperatur der E-Series wurde entfernt
 a| 
Das Flag für die Case-Erstellung ist jetzt für Ereignisse mit Überschreitung der nominalen und maximalen Temperatur deaktiviert, für die keine Aktion erforderlich ist.



 a| 
Flag zur Erstellung von Prioritätsfällen für das Ereignis 0x1209 Mel aktiviert
 a| 
Ein Flag für die Case-Erstellung wird jetzt für das erstellt `MEL_EV_DEGRADE_CHANNEL 0x1209` MEL-Ereignis.

|===