---
permalink: getting-started/learn-video-concept.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, E-Series videos 
summary: Sehen Sie sich Videodemos an, um mehr über die E-Series Systeme zu erfahren. 
---
= E-Series Videos
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sehen Sie sich Videodemos an, um mehr über die E-Series Systeme zu erfahren.



== E-Series: Schneller, einfacher und zuverlässiger Storage

[role="lead"]
Dieses Video zeigt die wichtigsten Vorteile der Verwendung von NetApp E-Series Systemen im Vergleich zur Verwendung von herkömmlichen Storage-Servern.

https://www.youtube.com/embed/FjFkU2z_hIo?rel=0["NetApp Video: Die wichtigsten Vorteile der Verwendung von NetApp E-Series Systemen im Vergleich zur Verwendung von Standard-Servern für Storage"^]



== System Manager: Einfache Einrichtung und Konfiguration

[role="lead"]
In dieser technischen Demo wird gezeigt, wie die webbasierte Benutzeroberfläche von SANtricity System Manager den Setup- und Konfigurations-Einsatz der NetApp E2800 vereinfacht.

https://www.youtube.com/embed/I0W0AjKpCO8?rel=0["NetApp Video: SANtricity System Manager: Einfache Einrichtung und Konfiguration"^]
