---
permalink: config-vmware/configure-multipath-software-concept.html 
sidebar: sidebar 
keywords: multipath software for vmware, express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, E4000, EF50, EF80, E-Series, eseries 
summary: Konfigurieren Sie Multipath-Software so, dass sie einen redundanten Pfad zum Storage Array bereitstellen kann, falls einer der physischen Pfade unterbrochen wird. 
---
= Konfigurieren Sie die Multipath-Software in der E-Series - VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Zum Bereitstellen eines redundanten Pfads zum Speichersystem ist die Konfiguration der Multipath-Software erforderlich.

Die Multipath-Software liefert einen redundanten Pfad zum Storage Array, falls ein physischer Pfad unterbrochen wird. Die Multipath-Software präsentiert das Betriebssystem mit einem einzigen virtuellen Gerät, das die aktiven physischen Pfade zum Storage darstellt. Die Multipath-Software managt auch den Failover-Prozess zur Aktualisierung des virtuellen Geräts.



[[multipathing-policies]]
== Multipathing-Richtlinien

Details zu den Multipathing-Richtlinien folgen unten. Für die Protokolle FCP, iSCSI und SAS ist standardmäßig Native Multipathing Plug-In (NMP) festgelegt. Für NVMe over Fabrics (NVMe over FC, NVMe over RoCE und NVMe over TCP) ist standardmäßig High Performance Plug-In (HPP) festgelegt.



[[native-multipathing-plug-ins-nmp]]
=== Native Multipathing Plug-Ins (NMP)

Gilt nur für die Protokolle FCP, iSCSI und SAS https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-1/vsphere-storage/understanding-multipathing-and-failover-in-the-esxi-environment/vmware-multipathing-module.html["VMware bietet Native Multipathing Plug-Ins (NMP) an"^], bekannt als Storage Array Type Plug-ins (SATP), zur Handhabung der Failover-Implementierungen von Storage Arrays bestimmter Anbieter.

Der zu verwendende SATP ist *VMW_SATP_ALUA* (dies ist die ausgewählte Standardeinstellung für NetApp E-Series). Weitere Informationen finden sich unter  https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-1/vsphere-storage/understanding-multipathing-and-failover-in-the-esxi-environment/vmware-satps.html["VMware SATA"^].



==== Plug-Ins und Richtlinien (PSP) für die Pfadauswahl

Diese Plug-ins sind Submodule des VMware NMP. Der NMP weist jedem logischen Gerät basierend auf dem Gerätetyp einen Standard-PSP zu. Sie können den Standard-PSP überschreiben. Weitere Informationen finden Sie unter https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-1/vsphere-storage/understanding-multipathing-and-failover-in-the-esxi-environment/viewing-and-managing-storage-paths-on-esxi-hosts/change-the-path-selection-policy.html["Ändern der Pfadauswahlrichtlinie"^]. Der NMP weist NetApp Geräten standardmäßig die Pfadauswahlrichtlinie VMW_PSP_RR (Round Robin) zu. Dies ist der empfohlene PSP.

Weitere Informationen finden sich unter  https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-1/vsphere-storage/understanding-multipathing-and-failover-in-the-esxi-environment/vmware-psps.html["VMware Pfadauswahl Plug-Ins und Richtlinien"^].



[[high-performance-plug-in-hpp]]
=== High Performance Plug-In (HPP)

Das HPP ersetzt das NMP für Hochgeschwindigkeitsgeräte wie NVMe. Das HPP ist das Standard-Plug-in, das NVMe-oF-Ziele beansprucht. ESX unterstützt durchgängiges NVMe ohne Emulation sowie SCSI-zu-NVMe-Emulation. Das HPP unterstützt nur Aktiv/Aktiv- und implizite ALUA-Ziele.



==== Pfadauswahlschemata (PSS)

Zur Unterstützung von Multipathing verwendet HPP bei der Auswahl physischer Pfade für E/A-Anforderungen die Pfadauswahlverfahren (PSS). Das Standardschema für von HPP beanspruchte Geräte ist LB-RR (Load Balance - Round Robin). Dies ist das empfohlene PSS.

Weitere Informationen zu HPP oder PSS finden Sie unter https://techdocs.broadcom.com/us/en/vmware-cis/vsphere/vsphere/9-1/vsphere-storage/understanding-multipathing-and-failover-in-the-esxi-environment/vmware-hpp.html["VMware High Performance Plug-In und Pfadauswahlschemata"^].
