---
permalink: config-vmware/discover-storage-host-task.html 
sidebar: sidebar 
keywords: discover storage ESXi, express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Nachdem Sie Volumes zum Host zugewiesen haben, führen Sie einen erneuten Scan durch, sodass der Host die Volumes für das Multipathing erkennt und konfiguriert. 
---
= Ermitteln Sie Storage auf dem Host in der E-Series – VMware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Nachdem Sie Volumes zum Host zugewiesen haben, führen Sie einen erneuten Scan durch, sodass der Host die Volumes für das Multipathing erkennt und konfiguriert.

Standardmäßig führt ein ESXi Host automatisch alle fünf Minuten einen erneuten Scan durch. Möglicherweise wird ein Volume zwischen dem Zeitpunkt der Erstellung und der Zuordnung zu einem Host angezeigt, bevor Sie einen manuellen erneuten Scan durchführen. Unabhängig davon können Sie einen manuellen erneuten Scan durchführen, um sicherzustellen, dass alle Volumes ordnungsgemäß konfiguriert wurden.

.Schritte
. Erstellen Sie ein oder mehrere Volumes, und weisen Sie sie dem ESXi-Host zu.
. Wenn Sie einen vCenter Server verwenden, fügen Sie den Host zum Server-Inventar hinzu.
. Verwenden Sie den vSphere Client oder vSphere Web Client, um eine direkte Verbindung zum vCenter Server oder zum ESXi Host herzustellen.
. Anweisungen zum erneuten Scannen des Speichers auf einem ESXi-Host finden Sie in dem https://support.broadcom.com/["VMware Knowledge Base"^] Artikel zu diesem Thema.

