---
permalink: config-vmware/verify-vmware-config-support-task.html 
sidebar: sidebar 
keywords: express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, EF50, EF80, E4000, E-Series, eseries 
summary: Vergewissern Sie sich, dass die VMware Konfiguration unterstützt wird. 
---
= Überprüfen Sie die Unterstützung der VMware-Konfiguration in der E-Series
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um einen zuverlässigen Betrieb zu gewährleisten, erstellen Sie einen Implementierungsplan und überprüfen mit dem NetApp Interoperabilitäts-Matrix-Tool (IMT) die Unterstützung der gesamten Konfiguration.

.Schritte
. Wechseln Sie zum http://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].
. Klicken Sie auf die Kachel * Solution Search*.
. Klicken Sie im Menü:Protokolle[SAN Host] auf die Schaltfläche *Hinzufügen* neben *E-Series SAN-Host*.
. Klicken Sie Auf *Suchkriterien Verfeinern*.
+
Der Abschnitt Suchkriterien verfeinern wird angezeigt. In diesem Abschnitt können Sie das zutreffende Protokoll sowie andere Kriterien für die Konfiguration auswählen, z. B. Betriebssystem, NetApp OS und Host Multipath-Treiber. Wählen Sie die Kriterien aus, die Sie für Ihre Konfiguration kennen, und sehen Sie dann, welche kompatiblen Konfigurationselemente gelten. Führen Sie bei Bedarf die Updates für Ihr Betriebssystem und Protokoll durch, die im Tool vorgeschrieben sind. Detaillierte Informationen zu der von Ihnen gewählten Konfiguration finden Sie auf der Seite Unterstützte Konfigurationen anzeigen, indem Sie auf den rechten Seitenpfeil klicken.

. Nehmen Sie bei Bedarf die in der Tabelle aufgeführten Aktualisierungen für Ihr Betriebssystem und Protokoll vor.
+
|===
| Betriebssystem-Updates | Protokoll | Protokollbezogene Updates 


 a| 
** Möglicherweise müssen Sie Out-of-Box-Treiber installieren, um die Funktionalität und den Support zu gewährleisten. Sie können HBA-Treiber mithilfe der ESXi Shell oder einer Remote-SSH-Verbindung zum ESXi Host installieren. Um mit einer dieser Methoden auf den Host zuzugreifen, müssen Sie den ESXi Shell- und SSH-Zugriff aktivieren. Weitere Informationen zur ESXi Shell finden Sie in der VMware Knowledge Base zur Verwendung der ESXi Shell in ESXi. Informationen zu Installationsbefehlen finden Sie in den Anweisungen zu den HBA-Treibern.
** Jeder HBA-Hersteller verwendet spezifische Methoden zum Aktualisieren von Bootcode und Firmware. Einige dieser Methoden können die Verwendung eines vCenter Plugins oder die Installation eines CIM-Providers auf dem ESXi-Host umfassen. vCenter Plugins können verwendet werden, um Informationen über das jeweilige HBA des Herstellers zu erhalten. Informationen zu den Anweisungen und der Software, die zum Aktualisieren des HBA-Bootcodes oder der Firmware erforderlich sind, finden Sie im Supportbereich der Website des Herstellers. Informationen dazu finden Sie im  https://compatibilityguide.broadcom.com/search?program=io&persona=live&column=brandName&order=asc["_VMware Compatibility Guide_"] oder auf der Website des HBA-Herstellers, um den richtigen Bootcode oder die richtige Firmware zu erhalten.
** Prüfen Sie Warnungen und Informationen im Zusammenhang mit der ausgewählten Konfiguration auf spezifische Betriebssystem-, Gastbetriebssystem-, HBA- oder andere relevante Einstellungen bzw. Informationen, die möglicherweise auf Ihre Konfiguration angewendet werden müssen.

 a| 
FCP
 a| 
Host Bus Adapter (HBA)-Treiber, Firmware und Bootcode



 a| 
ISCSI
 a| 
NIC-Treiber (Network Interface Card), Firmware und Bootcode



 a| 
SAS
 a| 
Host Bus Adapter (HBA)-Treiber, Firmware und Bootcode



 a| 
NVMe über FC
 a| 
Host Bus Adapter (HBA)-Treiber, Firmware und Bootcode



 a| 
NVMe over RoCE
 a| 
Remote Direct Memory Access (RDMA) Treiber, Firmware und Bootcode



 a| 
NVMe über TCP
 a| 
NIC-Treiber (Network Interface Card), Firmware und Bootcode

|===

