---
permalink: config-vmware/verify-vmware-config-support-task.html 
sidebar: sidebar 
keywords: express vmware configuration, software configuration, vmware host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Vergewissern Sie sich, dass die VMware Konfiguration unterstützt wird. 
---
= Überprüfen Sie, ob die VMware Konfiguration unterstützt wird
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um einen zuverlässigen Betrieb zu gewährleisten, erstellen Sie einen Implementierungsplan und überprüfen mit dem NetApp Interoperabilitäts-Matrix-Tool (IMT) die Unterstützung der gesamten Konfiguration.

.Schritte
. Wechseln Sie zum http://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].
. Klicken Sie auf die Kachel * Solution Search*.
. Klicken Sie im Menü:Protokolle[SAN Host] auf die Schaltfläche *Hinzufügen* neben *E-Series SAN-Host*.
. Klicken Sie Auf *Suchkriterien Verfeinern*.
+
Der Abschnitt Suchkriterien verfeinern wird angezeigt. In diesem Abschnitt können Sie das zutreffende Protokoll sowie andere Kriterien für die Konfiguration auswählen, z. B. Betriebssystem, NetApp OS und Host Multipath-Treiber. Wählen Sie die Kriterien aus, die Sie für Ihre Konfiguration kennen, und sehen Sie dann, welche kompatiblen Konfigurationselemente gelten. Führen Sie bei Bedarf die Updates für Ihr Betriebssystem und Protokoll durch, die im Tool vorgeschrieben sind. Detaillierte Informationen zu der von Ihnen gewählten Konfiguration finden Sie auf der Seite Unterstützte Konfigurationen anzeigen, indem Sie auf den rechten Seitenpfeil klicken.

. Nehmen Sie bei Bedarf die in der Tabelle aufgeführten Aktualisierungen für Ihr Betriebssystem und Protokoll vor.
+
|===
| Betriebssystem-Updates | Protokoll | Protokollbezogene Updates 


 a| 
** Möglicherweise müssen Sie Out-of-Box-Treiber installieren, um die Funktionalität und den Support zu gewährleisten. Sie können HBA-Treiber mithilfe der ESXi Shell oder einer Remote-SSH-Verbindung zum ESXi Host installieren. Um mit einer dieser Methoden auf den Host zuzugreifen, müssen Sie den ESXi Shell- und SSH-Zugriff aktivieren. Weitere Informationen zur ESXi Shell finden Sie in der VMware Knowledge Base zur Verwendung der ESXi Shell in ESXi. Informationen zu Installationsbefehlen finden Sie in den Anweisungen zu den HBA-Treibern.
** Jeder HBA-Anbieter verfügt über spezifische Methoden zur Aktualisierung des Boot-Codes und der Firmware. Einige dieser Methoden könnten die Verwendung eines vCenter-Plugins oder die Installation des CIM-Providers auf dem ESXi-Host beinhalten. Mit vCenter-Plugins erhalten Sie Informationen über den spezifischen HBA des Anbieters. Im Support-Abschnitt auf der Website des Anbieters finden Sie die Anweisungen und Software, die zur Aktualisierung des HBA-Startcodes oder der Firmware erforderlich sind. Informationen zum korrekten Startcode oder der korrekten Firmware erhalten Sie im _VMware Compatibility Guide_ oder auf der Website des HBA-Anbieters.

 a| 
FC
 a| 
Host Bus Adapter (HBA)-Treiber, Firmware und Bootcode



 a| 
ISCSI
 a| 
NIC-Treiber (Network Interface Card), Firmware und Bootcode



 a| 
SAS
 a| 
Host Bus Adapter (HBA)-Treiber, Firmware und Bootcode

|===

