---
sidebar: sidebar 
permalink: vcenter-plugin/san-spvc-ic-installation.html 
keywords: install vCenter plugin, installing vCenter plugin, vCenter plugin, 
summary: SANtricity Storage Plug-in für vCenter installieren oder aktualisieren 
---
= Installieren oder aktualisieren Sie das Storage Plug-in für vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Führen Sie diese Schritte aus, um das Storage Plug-in für vCenter zu installieren und die Plugin-Registrierung zu überprüfen. Sie können das Plugin auch mit diesen Anweisungen aktualisieren.



== Installationsvoraussetzungen prüfen

Stellen Sie sicher, dass Ihre Systeme die Anforderungen in erfüllen link:san-spvc-ic-reqs.html["Installations- und Upgrade-Anforderungen prüfen"].


NOTE: Die *vcenter.properties*-Dateien werden durch den Aktualisierungsprozess nicht beibehalten. Wenn Sie ein Upgrade durchführen, müssen Sie die Registrierung des Plugins vor dem Upgrade aufheben. Sobald das Upgrade erfolgreich abgeschlossen wurde, können Sie das Plugin wieder bei der vCSA registrieren.



== Installieren Sie die Plug-in-Software

So installieren Sie die Plugin-Software:

. Kopieren Sie die Installer-Datei auf den Host, der als Anwendungsserver verwendet wird, und greifen Sie dann auf den Ordner zu, in dem Sie das Installationsprogramm heruntergeladen haben.
. Doppelklicken Sie auf die Installationsdatei:
+
`santricity_storage_vcenterplugin-windows_x64-- nn.nn.nn.nnnn.exe`

+
Im obigen Dateinamen, `nn.nn.nn.nnnn` Stellt die Versionsnummer dar.

. Wenn die Installation beginnt, befolgen Sie die Anweisungen auf dem Bildschirm, um mehrere Funktionen zu aktivieren und einige Konfigurationsparameter einzugeben. Bei Bedarf können Sie eine dieser Optionen später in den Konfigurationsdateien ändern.
+

NOTE: Während eines Upgrades werden keine Konfigurationsparameter angezeigt.

+

NOTE: Während der Installation werden Sie zur Zertifikatvalidierung aufgefordert. Aktivieren Sie das Kontrollkästchen, wenn Sie die Zertifikatvalidierung zwischen dem Plug-in und den Speicher-Arrays durchsetzen möchten. Bei dieser Durchsetzung werden die Speicherarrayzertifikate auf Vertrauen in das Plug-in geprüft. Wenn die Zertifikate nicht vertrauenswürdig sind, dürfen sie dem Plugin nicht hinzugefügt werden. Wenn Sie die Zertifikatvalidierung überschreiben möchten, deaktivieren Sie das Kontrollkästchen, damit alle Speicher-Arrays mit selbstsignierten Zertifikaten zum Plugin hinzugefügt werden können. Weitere Informationen zu Zertifikaten finden Sie in der Online-Hilfe, die über die Plug-in-Schnittstelle verfügbar ist.

. Wenn die Meldung Webserver gestartet angezeigt wird, klicken Sie auf *OK*, um die Installation abzuschließen, und klicken Sie dann auf *Fertig*.
. Überprüfen Sie, ob der Anwendungsserver erfolgreich installiert wurde, indem Sie den Befehl *Services.msc* ausführen.
. Überprüfen Sie, ob der Application Server (VCP)-Service *NetApp SANtricity Storage Plug-in für vCenter* installiert war und der Service gestartet wurde.
+

NOTE: Bei Bedarf können Sie die Einstellungen für Zertifikatvalidierung und Webservice-Port nach der Installation ändern. Öffnen Sie im Installationsverzeichnis die Datei wsconfig.xml. Um die Zertifikatvalidierung auf Speicherarrays zu entfernen, ändern Sie das `env` Schlüssel, `trust.all.arrays`, An `true`. Ändern Sie den Web Services-Port, wenn Sie den ändern möchten `sslport` Wert bis zum gewünschten Portwert im Bereich von 0-65535. Stellen Sie sicher, dass die verwendete Portnummer keine Bindung an einen anderen Prozess hat. Wenn Sie fertig sind, speichern Sie die Änderungen und starten Sie den Plugin Webserver neu. Wenn der Portwert des Plugin-Webservers nach der Registrierung des Plugins in einem vCSA geändert wird, müssen Sie das Plugin unregistrieren und neu registrieren, damit der vCSA auf dem geänderten Port an den Plugin-Webserver kommuniziert.





== Registrieren Sie das Plug-in mit einer vCenter Server Appliance

Nachdem die Plugin-Software installiert ist, registrieren Sie das Plugin mit einem vCSA.


NOTE: Das Plugin kann nur jeweils auf einer vCSA registriert werden. Um sich bei einem anderen vCSA zu registrieren, müssen Sie das Plugin von der aktuellen vCSA deinstallieren und es vom Anwendungs-Host deinstallieren. Sie können dann das Plugin neu installieren und es auf dem anderen vCSA registrieren.

. Öffnen Sie eine Eingabeaufforderung über die Befehlszeile, und navigieren Sie zum folgenden Verzeichnis:
+
`<install directory>\vcenter-register\bin`

. Führen Sie die Datei *vcenter-Register.bat* aus:
`vcenter-register.bat ^
    -action registerPlugin ^
    -vcenterHostname <vCenter FQDN> ^
    -username <Administrator username> ^`
. Überprüfen Sie, ob das Skript erfolgreich war.


Die Protokolle werden in gespeichert `%install_dir%/working/logs/vc-registration.log`.



== Überprüfen Sie die Plugin-Registrierung

Nachdem das Plugin installiert und das Registrierungsskript ausgeführt wurde, überprüfen Sie, ob das Plugin bei der vCenter Server Appliance erfolgreich registriert wurde.

. Öffnen Sie vSphere Client auf der vCenter Server Appliance.
. Wählen Sie in der Menüleiste Menü:Administrator[Client Plugins].
. Stellen Sie sicher, dass das Storage Plugin für vCenter als *aktiviert* aufgeführt ist.
+
Wenn das Plug-in als deaktiviert aufgeführt wird und eine Fehlermeldung anzeigt, dass es nicht mit dem Anwendungsserver kommunizieren kann, überprüfen Sie, ob die für den Anwendungsserver definierte Portnummer aktiviert ist, um alle Firewalls zu durchlaufen, die verwendet werden könnten. Die standardmäßige Portnummer des Anwendungsservers Transmission Control Protocol (TCP) ist 8445.


