---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-how-do-i-maintain-shelf-and-drawer-loss-protection.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Schutz vor Shelf- und Schubladenverlust für einen Pool oder eine Volume-Gruppe beibehalten 
---
= Wie kann ich den Schutz vor Schubladenausfall wahren?
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Verwenden Sie die in der folgenden Tabelle aufgeführten Kriterien, um den Schutz vor Shelf- und Schubladenverlusten für einen Pool oder eine Volume-Gruppe aufrechtzuerhalten.

|===
| Ebene | Kriterien für den Schutz vor Shelf-/Schubladenverlust | Mindestanzahl an Shelves/Schubladen erforderlich 


| Pool | Bei Shelfs darf der Pool nicht mehr als zwei Laufwerke in einem einzelnen Shelf enthalten. Bei Schubladen muss der Pool eine gleiche Anzahl von Laufwerken von jeder Schublade enthalten. | 6 für Regale 5 für Schubladen 


| RAID 6 | Die Volume-Gruppe enthält nicht mehr als zwei Laufwerke in einem einzelnen Shelf oder einer einzelnen Schublade. | 3 


| RAID 3 oder RAID 5 | Jedes Laufwerk in der Volume-Gruppe befindet sich in einem separaten Shelf oder einer separaten Schublade. | 3 


| RAID 1 | Jedes Laufwerk in einem gespiegelten Paar muss sich in einem eigenen Shelf oder einer separaten Schublade befinden. | 2 


| RAID 0 | Schutz vor Shelf-/Schubladenverlust kann nicht erreicht werden. | Keine Angabe 
|===

NOTE: Der Schutz vor Shelf-/Schubladenverlust bleibt nicht erhalten, wenn ein Laufwerk bereits in dem Pool oder der Volume-Gruppe ausgefallen ist. Geht in dieser Situation der Zugriff auf ein Festplatten-Shelf oder eine Laufwerksschublade verloren und somit ein weiteres Laufwerk im Pool bzw. der Volume-Gruppe, geht es zu Datenverlusten.
