---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-how-do-i-view-and-interpret-all-ssd-cache-statistics.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Sie können nominale Statistiken und detaillierte Statistiken für SSD Cache anzeigen. 
---
= Wie kann ich sämtliche SSD Cache Statistiken anzeigen und interpretieren?
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können nominale Statistiken und detaillierte Statistiken für SSD Cache anzeigen.

Die Nominalstatistiken sind eine Untergruppe der detaillierten Statistiken. Die detaillierten Statistiken können nur angezeigt werden, wenn Sie alle SSD-Statistiken in eine .csv-Datei exportieren. Während Sie die Statistiken überprüfen und interpretieren, beachten Sie, dass einige Interpretationen durch die Prüfung einer Kombination von Statistiken abgeleitet werden.



=== Nominale Statistiken

Um SSD Cache Statistiken anzuzeigen, gehen Sie zur Seite *Verwalten*. Wählen Sie Menü:Provisioning[Pools & Volume-Gruppen konfigurieren]. Wählen Sie den SSD-Cache aus, für den Sie Statistiken anzeigen möchten, und wählen Sie dann Menü:Mehr[Statistik anzeigen]. Die nominalen Statistiken werden im Dialogfeld „View SSD Cache Statistics“ angezeigt.


NOTE: Diese Funktion steht nicht auf dem EF600 oder EF300-Storage-System zur Verfügung.

Die Liste enthält nominale Statistiken, die eine Untermenge der detaillierten Statistiken sind.



=== Detaillierte Statistiken

Die detaillierten Statistiken bestehen aus den Nominalstatistiken sowie zusätzlichen Statistiken. Diese zusätzlichen Statistiken werden zusammen mit den nominalen Statistiken gespeichert, werden aber im Gegensatz zu den nominalen Statistiken nicht im Dialogfeld „View SSD Cache Statistics“ angezeigt. Sie können die detaillierten Statistiken nur anzeigen, nachdem Sie die Statistiken in eine CSV-Datei exportiert haben.

Die detaillierten Statistiken sind nach den Nominalstatistiken aufgelistet.
