---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-discover-storage-arrays.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Um Speicherressourcen im Storage Plug-in für vCenter anzuzeigen und zu verwalten, müssen Sie die IP-Adressen von Arrays in Ihrem Netzwerk ermitteln. 
---
= Erkennen Sie Storage-Arrays
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Um Speicherressourcen im Storage Plug-in für vCenter anzuzeigen und zu verwalten, müssen Sie die IP-Adressen von Arrays in Ihrem Netzwerk ermitteln.

.Bevor Sie beginnen
* Sie müssen die Netzwerk-IP-Adressen (oder den Adressbereich) der Array-Controller kennen.
* Die Speicher-Arrays müssen ordnungsgemäß eingerichtet und konfiguriert sein.
* Passwörter für das Storage-Array müssen mithilfe der Kachel „System Manager Access Management“ eingerichtet werden.


Die Array-Erkennung ist ein mehrstufiges Verfahren:

*  1: Enter network addresses for discovery
*  2: Resolve untrusted certificates during discovery
*  3: Provide passwords




== Schritt 1: Geben Sie Netzwerkadressen für die Ermittlung ein

Als erster Schritt zur Ermittlung von Speicherarrays geben Sie eine einzelne IP-Adresse oder eine Reihe von IP-Adressen ein, um im lokalen Teilnetzwerk zu suchen. Die Funktion Hinzufügen/Entdecken öffnet einen Assistenten, der Sie durch den Erkennungsprozess führt.

.Schritte
. Wählen Sie auf der Seite *Verwalten* die Option *Hinzufügen/Entdecken*.
+
Das Dialogfeld Netzwerkadressbereich eingeben wird angezeigt.

. Führen Sie einen der folgenden Schritte aus:
+
** Um ein Array zu ermitteln, wählen Sie die Optionsschaltfläche *Entdecken eines einzelnen Speicherarrays* aus und geben dann die IP-Adresse für einen der Controller im Speicher-Array ein.
** Um mehrere Speicher-Arrays zu entdecken, wählen Sie die Optionsschaltfläche *Alle Speicher-Arrays in einem Netzwerkbereich* aus. Geben Sie dann die Startnetzwerkadresse und die Netzwerkadresse ein, um das lokale Subnetzwerk zu durchsuchen.


. Klicken Sie Auf *Erkennung Starten*.
+
Beim Beginn des Erkennungsvorgangs werden die Speicher-Arrays im Dialogfeld angezeigt, wenn sie erkannt werden. Der Erkennungsvorgang kann mehrere Minuten dauern.

+

NOTE: Wenn keine verwaltbaren Arrays erkannt werden, überprüfen Sie, ob die Speicher-Arrays ordnungsgemäß mit Ihrem Netzwerk verbunden sind und die zugewiesenen Adressen innerhalb der Reichweite liegen. Klicken Sie auf *Neue Ermittlungsparameter*, um zur Seite Hinzufügen/Entdecken zurückzukehren.

. Aktivieren Sie das Kontrollkästchen neben einem beliebigen Speicher-Array, das Sie Ihrer Management-Domäne hinzufügen möchten.
+
Das System führt eine Anmeldeinformationen für jedes Array aus, das Sie der Management-Domäne hinzufügen. Möglicherweise müssen Sie Probleme mit nicht vertrauenswürdigen Zertifikaten beheben, bevor Sie fortfahren.

. Klicken Sie auf *Weiter*, um mit dem nächsten Schritt im Assistenten fortzufahren.
. Wenn die Speicher-Arrays über gültige Zertifikate verfügen, gehen Sie zu  3: Provide passwords. Wenn keine Speicherarrays über gültige Zertifikate verfügen, wird das Dialogfeld Selbstsignierte Zertifikate auflösen angezeigt. Gehen Sie zu  2: Resolve untrusted certificates during discovery. Wenn Sie CA-signierte Zertifikate importieren möchten, löschen Sie die Ermittlungsdialoge und gehen Sie zu link:vc-olh-import-certificates-for-arrays.html["Importieren Sie Zertifikate für Arrays"].




== Schritt 2: Lösen Sie nicht vertrauenswürdige Zertifikate während der Ermittlung

Falls erforderlich, müssen Sie Zertifikatprobleme beheben, bevor Sie mit dem Erkennungsvorgang fortfahren.

Wenn während der Erkennung Speicherarrays den Status „nicht vertrauenswürdige Zertifikate“ aufweisen, wird das Dialogfeld Selbstsignierte Zertifikate auflösen angezeigt. In diesem Dialogfeld können Sie nicht vertrauenswürdige Zertifikate auflösen oder CA-Zertifikate importieren (siehe link:vc-olh-import-certificates-for-arrays.html["Importieren Sie Zertifikate für Arrays"]).

.Schritte
. Wenn das Dialogfeld selbst signierte Zertifikate auflösen geöffnet wird, überprüfen Sie die Informationen, die für die nicht vertrauenswürdigen Zertifikate angezeigt werden. Für weitere Informationen können Sie auch auf die Ellipsen am äußersten Ende der Tabelle klicken und im Kontextmenü *Ansicht* wählen.
. Führen Sie einen der folgenden Schritte aus:
+
** Wenn Sie den Verbindungen zu den erkannten Speicherarrays vertrauen, klicken Sie auf *Weiter* und klicken Sie dann auf *Ja*, um die nächste Karte im Assistenten zu bestätigen. Die selbstsignierten Zertifikate werden als vertrauenswürdig gekennzeichnet und die Speicher-Arrays werden dem Plugin hinzugefügt.
** Wenn Sie den Verbindungen zu den Speicher-Arrays nicht vertrauen, wählen Sie *Abbrechen* und validieren Sie die Sicherheitszertifikatstrategie jedes Speicherarrays, bevor Sie eine dieser Verbindungen zum Plugin hinzufügen.






== Schritt 3: Geben Sie Passwörter ein

Als letzter Schritt zur Ermittlung müssen Sie die Passwörter für die Speicherarrays eingeben, die Sie Ihrer Management-Domäne hinzufügen möchten.

.Schritte
. Wenn Sie bereits Gruppen für die Arrays konfiguriert haben, können Sie mit dem Dropdown-Menü eine Gruppe für die ermittelten Arrays auswählen.
. Geben Sie für jedes erkannte Array sein Administratorkennwort in die Felder ein.
. Klicken Sie Auf *Fertig Stellen*.



NOTE: Es kann mehrere Minuten dauern, bis das System eine Verbindung zu den angegebenen Speicherarrays herstellt.

Die Speicher-Arrays werden Ihrer Management-Domäne hinzugefügt und der ausgewählten Gruppe zugeordnet (falls angegeben).


NOTE: Sie können die Option Start verwenden, um den Browser-basierten System Manager für ein oder mehrere Speicher-Arrays zu öffnen, wenn Sie Managementvorgänge ausführen möchten.
