---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-clear-staged-os-software.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Sie können die stufenweise Betriebssystemsoftware entfernen, um sicherzustellen, dass eine ausstehende Version zu einem späteren Zeitpunkt nicht versehentlich aktiviert wird. 
---
= Software für das überstaltete Betriebssystem löschen
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die stufenweise Betriebssystemsoftware entfernen, um sicherzustellen, dass eine ausstehende Version zu einem späteren Zeitpunkt nicht versehentlich aktiviert wird. Das Entfernen der stufenweisen Betriebssystemsoftware hat keine Auswirkungen auf die aktuelle Version, die auf den Speicher-Arrays ausgeführt wird.

.Schritte
. Wählen Sie in der Hauptansicht *Verwalten* und dann Menü:SANtricity-Upgrade[Staged--Software löschen].
+
Das Dialogfeld „Staged SANtricity-Software löschen“ wird geöffnet und listet alle erkannten Speichersysteme mit ausstehender Software oder NVSRAM auf.

. Filtern oder sortieren Sie die Speichersysteme in der Liste, falls erforderlich, so dass Sie alle Systeme mit stufenweise Software anzeigen können.
. Aktivieren Sie die Kontrollkästchen für die Speichersysteme mit ausstehender Software, die Sie löschen möchten.
. Klicken Sie Auf *Löschen*.
+
Der Status des Vorgangs wird im Dialogfeld angezeigt.


