---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-what-do-i-need-to-know-about-the-resource-provisioned-volumes-feature.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Resource Provisioning ist eine Funktion, die in den EF300- und EF600-Speicher-Arrays zur Verfügung steht und die es ermöglicht, Volumes ohne Hintergrundinitialisierung sofort in Betrieb zu nehmen. 
---
= Was muss ich über die Funktion der Ressourcen-bereitgestellten Volumes wissen?
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Resource Provisioning ist eine Funktion, die in den EF300- und EF600-Speicher-Arrays zur Verfügung steht und die es ermöglicht, Volumes ohne Hintergrundinitialisierung sofort in Betrieb zu nehmen.


NOTE: Die Ressourcen-Provisioning-Funktion ist derzeit nicht verfügbar. In einigen Ansichten können Komponenten als ressourcenschonende Bereitstellung gemeldet werden, aber die Möglichkeit, mit Ressourcen bereitgestellte Volumes zu erstellen, wurde deaktiviert, bis sie in einem zukünftigen Update erneut aktiviert werden kann.



== Volumes mit Ressourcenbereitstellung

Ein vom Ressourcen bereitgestelltes Volume ist ein Thick Volume in einer SSD-Volume-Gruppe oder einem Pool. Dabei wird bei der Erstellung des Volume die Laufwerkskapazität zugewiesen (dem Volume zugewiesen), die Laufwerksblöcke jedoch aufgehoben (nicht zugewiesen). In einem herkömmlichen Thick Volume werden im Vergleich dazu alle Laufwerkblöcke während der Initialisierung eines Volume im Hintergrund zugeordnet oder zugewiesen, um die Felder für den Schutz der Data Assurance zu initialisieren und die Daten- und RAID-Parität in jedem RAID Stripe konsistent zu gestalten. Bei einem Volume, das für die Ressource bereitgestellt wird, gibt es keine zeitgebundene Hintergrundinitialisierung. Stattdessen wird jeder RAID-Stripe nach dem ersten Schreibvorgang auf einen Volume-Block im Stripe initialisiert.

Über Ressourcen bereitgestellte Volumes werden nur auf SSD-Volume-Gruppen und -Pools unterstützt, wobei alle Laufwerke in der Gruppe oder dem Pool die nicht zugewiesene oder nicht geschriebene DULBE-Fehlerwiederherstellungsfunktion (Logical Block Error Enable) unterstützen. Bei der Erstellung eines Volume mit Ressourcenbereitstellung werden alle dem Volume zugewiesenen Festplattenblöcke wieder zugewiesen (Zuordnung). Zudem können Hosts mithilfe des NVMe-Datensatzmanagements logische Blöcke im Volume deallokalisieren. Die Deallokung von Blöcken kann die SSD-Abnutzung verbessern und die maximale Schreib-Performance erhöhen. Die Verbesserung variiert je nach Modell und Kapazität der Laufwerke.



== Aktivieren und Deaktivieren der Funktion

Die Ressourcenbereitstellung ist standardmäßig auf Systemen aktiviert, auf denen die Laufwerke DULBE unterstützen. Sie können diese Standardeinstellung in Pools und Volume-Gruppen deaktivieren. Die Deaktivierung der Ressourcen-Bereitstellung ist eine permanente Aktion für vorhandene Volumes und kann nicht rückgängig gemacht werden (d. h. Sie können die Ressourcen-Bereitstellung für diese Volume-Gruppen und -Pools nicht erneut aktivieren).

Wenn Sie die Ressourcenbereitstellung jedoch für alle von Ihnen erstellten neuen Volumes erneut aktivieren möchten, können Sie dies über das Menü:Einstellungen[System] tun. Beachten Sie, dass bei der erneuten Aktivierung der Ressourcenbereitstellung nur neu erstellte Volume-Gruppen und Pools betroffen sind. Alle vorhandenen Volume-Gruppen und -Pools bleiben unverändert. Bei Bedarf können Sie die Ressourcenbereitstellung auch wieder über das Menü:Einstellungen[System] deaktivieren.
