---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-import-certificates-for-arrays.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Importieren von Zertifikaten für die Speicher-Arrays, damit sie sich mit dem System authentifizieren können, das das Storage Plug-in für vCenter hostet. 
---
= Importieren Sie Zertifikate für Arrays
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Bei Bedarf können Zertifikate für die Speicher-Arrays importiert werden, sodass sie sich mit dem System authentifizieren können, das das Storage Plug-in für vCenter hostet. Zertifikate können von einer Zertifizierungsstelle (CA) signiert oder selbst signiert werden.

Wenn Sie vertrauenswürdige Zertifikate importieren, müssen die Zertifikate für die Speicher-Array-Controller mit System Manager importiert werden.

.Schritte
. Wählen Sie *Zertifikatverwaltung*.
. Wählen Sie die Registerkarte * Trusted* aus.
+
Auf dieser Seite werden alle Zertifikate angezeigt, die für die Speicher-Arrays gemeldet wurden.

. Wählen Sie entweder Menü:Import[Certificates], um ein CA-Zertifikat oder Menü zu importieren:Importieren[Self-signierte Speicher-Array-Zertifikate], um ein selbstsigniertes Zertifikat zu importieren.
. Um die Ansicht einzuschränken, können Sie das Filterfeld *Zertifikate anzeigen verwenden, das...* ist, oder Sie können die Zertifikatzeilen sortieren, indem Sie auf eine der Spaltenüberschrift klicken.
. Wählen Sie im Dialogfeld das Zertifikat aus und klicken Sie dann auf *Import*.
+
Das Zertifikat wird hochgeladen und validiert.


