---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-provisioning-overview.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Sie können Daten-Container namens Volumes erstellen, damit der Host auf den Storage im Array zugreifen kann. 
---
= Provisioning – Überblick
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Im Storage Plug-in für vCenter können Sie Daten-Container, sogenannte Volumes, erstellen, sodass der Host auf den Storage im Array zugreifen kann.



== Volume-Typen und -Eigenschaften

Volumes sind Daten-Container, die den Speicherplatz auf Ihrem Storage-Array managen und organisieren.

Sie erstellen Volumes aus der Speicherkapazität, die auf Ihrem Speicher-Array verfügbar ist, was Ihnen hilft, die Ressourcen Ihres Systems zu organisieren. Das Konzept der "Volumes" ist ähnlich wie die Verwendung von Ordnern/Verzeichnissen auf einem Computer, um Dateien für schnellen Zugriff zu organisieren.

Volumes sind die einzige Datenebene, die Hosts sichtbar ist. In einer SAN-Umgebung werden Volumes den Logical Unit Numbers (LUNs) zugeordnet. Diese LUNs enthalten die Benutzerdaten, auf die über ein oder mehrere der vom Storage Array unterstützten Host-Zugriffsprotokolle zugegriffen werden kann, einschließlich FC, iSCSI und SAS.

Jedes Volume in einem Pool oder Volume-Gruppe kann je nach Art der Daten seine eigenen, individuellen Eigenschaften aufweisen. Einige dieser Eigenschaften sind:

* *Segmentgröße* -- Ein Segment ist die Datenmenge in Kilobyte (KiB), die auf einem Laufwerk gespeichert ist, bevor das Speicherarray zum nächsten Laufwerk im Stripe (RAID-Gruppe) wechselt. Die Segmentgröße ist gleich oder kleiner als die Kapazität der Volume-Gruppe. Die Segmentgröße ist festgelegt und kann für Pools nicht geändert werden.
* *Kapazität* -- Sie erstellen ein Volume aus der freien Kapazität, die entweder in einem Pool oder einer Volume-Gruppe verfügbar ist. Bevor Sie ein Volume erstellen, muss der Pool oder die Volume-Gruppe bereits vorhanden sein und genügend freie Kapazität zur Erstellung des Volumes haben.
* *Controller-Eigentum* -- Alle Speicher-Arrays können einen oder zwei Controller haben. Auf einem Single-Controller-Array wird die Workload eines Volumes von einem einzigen Controller verwaltet. Auf einem Dual-Controller-Array hat ein Volume einen bevorzugten Controller (A oder B), der das Volume „besitzt“. In einer Dual-Controller-Konfiguration wird die Eigentümerschaft von Volumes automatisch mithilfe der Funktion Automatischer Lastausgleich angepasst, um eventuelle Probleme beim Lastenausgleich bei der Workload-Verschiebung zwischen den Controllern zu beheben. Der automatische Lastausgleich ermöglicht einen automatisierten I/O-Workload-Ausgleich und sorgt dafür, dass eingehender I/O-Datenverkehr von den Hosts auf beiden Controllern dynamisch gemanagt und ausgeglichen wird.
* *Volume-Zuweisung* -- Sie können Hosts entweder bei der Erstellung des Volumes oder zu einem späteren Zeitpunkt auf ein Volume zugreifen. Der gesamte Host-Zugriff wird über eine LUN (Logical Unit Number) gemanagt. Hosts erkennen LUNs, die wiederum den Volumes zugewiesen sind. Wenn Sie ein Volume mehreren Hosts zuweisen, verwenden Sie eine Clustering-Software, um sicherzustellen, dass das Volume für alle Hosts verfügbar ist.
+
Der Host-Typ kann bestimmte Einschränkungen für die Anzahl der Volumes haben, auf die der Host zugreifen kann. Beachten Sie diese Einschränkung bei der Erstellung von Volumes zur Verwendung durch einen bestimmten Host.

* *Ressourcen-Provisioning* -- für EF600- oder EF300-Speicher-Arrays können Sie festlegen, dass Volumes ohne Hintergrundinitialisierung sofort verwendet werden. Ein vom Ressourcen bereitgestelltes Volume ist ein Thick Volume in einer SSD-Volume-Gruppe oder einem Pool. Dabei wird bei der Erstellung des Volume die Laufwerkskapazität zugewiesen (dem Volume zugewiesen), die Laufwerksblöcke jedoch aufgehoben (nicht zugewiesen).
* *Beschreibenden Name* -- Sie können ein Volumen benennen, welchen Namen Sie wollen, aber wir empfehlen, den Namen beschreibend zu machen.


Während der Volume-Erstellung wird jedem Volume Kapazität zugewiesen. Sie erhalten einen Namen, eine Segmentgröße (nur Volume-Gruppen), einen Controller-Besitz und eine Zuweisung von Volume zu Host. Bei Bedarf erfolgt ein automatischer Lastausgleich der Volume-Daten über Controller hinweg.



== Kapazität für Volumes

Die Laufwerke in Ihrem Speicher-Array stellen die physische Speicherkapazität für Ihre Daten bereit. Bevor Sie mit dem Speichern von Daten beginnen können, müssen Sie die zugewiesene Kapazität in logischen Komponenten – Pools oder Volume-Gruppen – konfigurieren. Mithilfe dieser Speicherobjekte lassen sich Daten auf dem Speicher-Array konfigurieren, speichern, verwalten und erhalten.



=== Kapazität zur Erstellung und Erweiterung von Volumes

Sie können Volumes entweder aus der nicht zugewiesenen Kapazität oder aus freien Kapazitäten in einem Pool oder einer Volume-Gruppe erstellen.

* Wenn Sie ein Volume aus nicht zugewiesenen Kapazitäten erstellen, können Sie gleichzeitig einen Pool oder eine Volume-Gruppe und das Volume erstellen.
* Wenn Sie ein Volume aus freier Kapazität erstellen, erstellen Sie ein zusätzliches Volume in einem bereits vorhandenen Pool oder einer Volume-Gruppe.Nachdem Sie die Volume-Kapazität erweitert haben, müssen Sie die Größe des Dateisystems manuell erhöhen, um sie anzupassen. Wie Sie dies tun, hängt von dem Dateisystem ab, das Sie verwenden. Weitere Informationen finden Sie in der Dokumentation Ihres Host-Betriebssystems.



NOTE: Die Plugin-Schnittstelle bietet keine Option zum Erstellen von Thin Volumes.



=== Gemeldete Kapazität für Volumes

Die gemeldete Kapazität des Volumes entspricht der Menge der zugewiesenen physischen Speicherkapazität. Es muss die gesamte physische Storage-Kapazität vorhanden sein. Der physisch zugewiesene Speicherplatz entspricht dem Speicherplatz, der dem Host gemeldet wird.

Normalerweise stellen Sie die gemeldete Kapazität des Volumes so ein, dass die maximale Kapazität, die Ihrer Meinung nach das Volume vergrößern wird. Volumes liefern eine hohe und vorhersehbare Performance für Ihre Applikationen, vor allem, weil sämtliche Benutzerkapazitäten reserviert und bei ihrer Erstellung zugewiesen sind.



=== Kapazitätsgrenzen

Die minimale Kapazität für ein Volume beträgt 1 MiB, und die maximale Kapazität hängt von der Anzahl und Kapazität der Laufwerke im Pool bzw. der Volume-Gruppe ab.

Beachten Sie bei der Erhöhung der gemeldeten Kapazität für ein Volumen die folgenden Richtlinien:

* Sie können bis zu drei Dezimalstellen (z. B. 65.375 gib) angeben.
* Die Kapazität muss kleiner sein als (oder gleich) die maximale in der Volume-Gruppe verfügbar ist. Wenn Sie ein Volume erstellen, wird für die DSS-Migration (Dynamic Segment Size) zusätzliche Kapazität vorab zugewiesen. Die DSS-Migration ist eine Funktion der Software, mit der Sie die Segmentgröße eines Volumes ändern können.
* Volumes mit einer Größe von mehr als 2 tib werden von einigen Host-Betriebssystemen unterstützt (die maximale gemeldete Kapazität wird vom Host-Betriebssystem bestimmt). Tatsächlich unterstützen einige Host-Betriebssysteme bis zu 128 tib Volumes. Weitere Informationen finden Sie in der Dokumentation Ihres Host-Betriebssystems.




== Applikationsspezifische Workloads

Wenn Sie ein Volume erstellen, wählen Sie einen Workload aus, um die Storage-Array-Konfiguration für eine bestimmte Applikation anzupassen.

Ein Workload ist ein Storage-Objekt, das eine Applikation unterstützt. Sie können einen oder mehrere Workloads oder Instanzen pro Applikation definieren. Bei einigen Applikationen konfiguriert das System den Workload so, dass er Volumes mit ähnlichen zugrunde liegenden Volume-Merkmalen enthält. Diese Volume-Merkmale werden basierend auf dem Applikationstyp optimiert, den der Workload unterstützt. Wenn Sie beispielsweise einen Workload erstellen, der eine Microsoft SQL Server Applikation unterstützt und anschließend Volumes für diesen Workload erstellt, werden die zugrunde liegenden Volume-Merkmale zur Unterstützung von Microsoft SQL Server optimiert.

Während der Volume-Erstellung werden Sie vom System aufgefordert, Fragen zur Verwendung eines Workloads zu beantworten. Wenn Sie beispielsweise Volumes für Microsoft Exchange erstellen, werden Sie gefragt, wie viele Mailboxen Sie benötigen, wie viele Mailboxen Ihre durchschnittlichen Anforderungen an die Mailbox-Kapazität sind und wie viele Kopien der Datenbank Sie benötigen. Das System erstellt anhand dieser Informationen eine optimale Volume-Konfiguration für Sie, die Sie nach Bedarf bearbeiten können. Optional können Sie diesen Schritt in der Sequenz zur Volume-Erstellung überspringen.



=== Workload-Typen

Es können zwei unterschiedliche Workload-Typen erstellt werden: Applikationsspezifisch oder sonstige.

* *Applikationsspezifisch* -- Wenn Sie Volumes mit einem anwendungsspezifischen Workload erstellen, empfiehlt das System möglicherweise eine optimierte Volume-Konfiguration, um Konflikte zwischen Applikations-Workload I/O und anderem Traffic aus Ihrer Anwendungsinstanz zu minimieren. Volume-Merkmale wie I/O-Typ, Segmentgröße, Controller-Besitz und Lese- und Schreib-Cache werden automatisch für Workloads empfohlen und optimiert, die für die folgenden Applikationstypen erstellt wurden.
+
** Microsoft SQL Server
** Microsoft Exchange Server
** Videoüberwachungsapplikationen
** VMware ESXi (für Volumes, die mit dem Virtual Machine File System verwendet werden sollen)
+
Sie können die empfohlene Volume-Konfiguration überprüfen und die vom System empfohlenen Volumes und Merkmale bearbeiten, hinzufügen oder löschen. Verwenden Sie dazu das Dialogfeld Volumes hinzufügen/bearbeiten.



* *Andere (oder Anwendungen ohne spezifische Unterstützung der Volumenerzeugung)* -- Bei anderen Workloads wird eine Volume-Konfiguration verwendet, die manuell angegeben werden muss, wann ein Workload erstellt werden soll, der nicht mit einer bestimmten Applikation verknüpft ist, oder ob das System keine integrierte Optimierung für die Applikation bietet, die Sie im Storage-Array verwenden möchten. Sie müssen die Volume-Konfiguration manuell über das Dialogfeld Volumes hinzufügen/bearbeiten angeben.




=== Anzeige von Applikationen und Workloads

Um Anwendungen und Workloads anzuzeigen, starten Sie System Manager. Über diese Schnittstelle können Sie die Informationen anzeigen, die mit einem applikationsspezifischen Workload verknüpft sind. Sie haben verschiedene Möglichkeiten:

* Sie können die Registerkarte Anwendungen & Workloads in der Kachel Volumes auswählen, um die Volumes des Speicherarrays nach Workload gruppiert und den Anwendungstyp, mit dem der Workload verknüpft ist, anzuzeigen.
* Über die Registerkarte Applikationen und Workloads im Tile Performance können Sie Performance-Metriken (Latenz, IOPS und MB) für logische Objekte anzeigen. Die Objekte werden nach Applikation und zugehörieinem Workload gruppiert. Indem Sie diese Performance-Daten in regelmäßigen Abständen erfassen, können Sie Basismessungen vornehmen und Trends analysieren. Dies unterstützt Sie bei der Untersuchung von I/O-Performance-Problemen.

