---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-create-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Sie können eine Volume-Gruppe für ein oder mehrere Volumes erstellen, auf die der Host zugreifen kann. 
---
= Erstellen einer Volume-Gruppe
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können eine Volume-Gruppe für ein oder mehrere Volumes erstellen, auf die der Host zugreifen kann. Eine Volume-Gruppe ist ein Container für Volumes mit gemeinsam genutzten Merkmalen wie RAID-Level und Kapazität.

.Bevor Sie beginnen
Lesen Sie sich die folgenden Richtlinien durch:

* Sie benötigen mindestens ein nicht zugewiesenes Laufwerk.
* Einschränkungen gibt es hinsichtlich der Laufwerkskapazität, die Sie in einer einzelnen Volume-Gruppe haben können. Diese Einschränkungen variieren je nach Hosttyp.
* Um einen Verlust von Shelfs/Schubladen zu ermöglichen, müssen Sie eine Volume-Gruppe erstellen, die Laufwerke in mindestens drei Shelfs oder Schubladen verwendet, es sei denn, Sie verwenden RAID 1, wo mindestens zwei Shelfs/Schubladen verwendet werden.
* Wenn Sie ein EF600 oder EF300 Storage-Array konfigurieren, stellen Sie sicher, dass jeder Controller in den ersten 12 Steckplätzen und in den letzten 12 Steckplätzen Zugriff auf eine gleiche Anzahl von Laufwerken hat. Mit dieser Konfiguration können die Controller beide PCIe-Busse auf der Laufwerkseite effektiver nutzen. Das System ermöglicht derzeit die Laufwerkauswahl unter der Funktion Erweitert, wenn eine Volume-Gruppe erstellt wird.


Überprüfen Sie, wie sich die RAID-Auswahl auf die resultierende Kapazität der Volume-Gruppe auswirkt.

* Wenn Sie RAID 1 auswählen, müssen Sie jeweils zwei Laufwerke hinzufügen, um sicherzustellen, dass ein gespiegeltes Paar ausgewählt ist. Spiegelung und Striping (bekannt als RAID 10 oder RAID 1+0) wird erreicht, wenn vier oder mehr Laufwerke ausgewählt werden.
* Wenn Sie RAID 5 auswählen, müssen Sie mindestens drei Laufwerke hinzufügen, um die Volume-Gruppe zu erstellen.
* Wenn Sie RAID 6 auswählen, müssen Sie mindestens fünf Laufwerke hinzufügen, um die Volume-Gruppe zu erstellen.


.Über diese Aufgabe
Bei der Erstellung von Volume-Gruppen bestimmen Sie die Gruppenmerkmale, z. B. die Anzahl an Laufwerken, die Sicherheitsfunktion, die Data Assurance (da)-Funktion, den Schutz vor Shelf-Datenverlusten und den Schutz vor Schubladenverlust.

Für EF600 und EF300 Storage-Arrays umfassen die Einstellungen auch die Ressourcenbereitstellung, die Laufwerksblockgrößen und die Volume-Blockgrößen.


NOTE: Mit Laufwerken mit größerer Kapazität und der Möglichkeit, Volumes über Controller hinweg zu verteilen, bietet das Erstellen von mehr als einem Volume pro Volume-Gruppe eine gute Möglichkeit, die Storage-Kapazität zu nutzen und die Daten zu sichern.

.Schritte
. Wählen Sie auf der Seite Verwalten das Speicher-Array für die Volume-Gruppe aus.
. Wählen Sie Menü:Provisioning[Pools und Volume-Gruppen konfigurieren].
. Klicken Sie auf Menü:Erstellen[Volume Group].
+
Das Dialogfeld Volume-Gruppe erstellen wird angezeigt.

. Geben Sie einen Namen für die Volume-Gruppe ein.
. Wählen Sie das RAID Level aus, das Ihre Anforderungen an Storage und Datensicherheit am besten erfüllt. Die Kandidatentabelle für die Volume-Gruppe wird angezeigt und zeigt nur die Kandidaten an, die die ausgewählte RAID-Ebene unterstützen.
. (Optional) Wenn Sie mehr als einen Laufwerkstyp im Speicher-Array haben, wählen Sie den Laufwerkstyp aus, den Sie verwenden möchten.
+
Die Kandidatentabelle für die Volume-Gruppe wird angezeigt und zeigt nur die Kandidaten an, die den ausgewählten Laufwerkstyp und den ausgewählten RAID-Level unterstützen.

. (Optional) Sie können entweder die automatische oder die manuelle Methode auswählen, um festzulegen, welche Laufwerke in der Volume-Gruppe verwendet werden sollen. Die automatische Methode ist die Standardauswahl.
+

CAUTION: Verwenden Sie die manuelle Methode nur, wenn Sie ein Experte sind, der die Redundanz und die optimale Laufwerkskonfiguration versteht.

+
Um Laufwerke manuell auszuwählen, klicken Sie auf den Link *Manuelle Auswahl von Laufwerken (erweitert)*. Wenn Sie auf diese Schaltfläche klicken, wird die Option *automatisch Laufwerke auswählen (erweitert)*.

+
Mit der manuellen Methode können Sie auswählen, welche spezifischen Laufwerke die Volume-Gruppe umfassen. Wählen Sie bestimmte nicht zugewiesene Laufwerke aus, um die erforderliche Kapazität abzurufen. Wenn das Speicher-Array Laufwerke mit unterschiedlichen Medientypen oder unterschiedlichen Schnittstellentypen enthält, können Sie nur die nicht konfigurierte Kapazität für einen einzelnen Laufwerkstyp auswählen, um die neue Volume-Gruppe zu erstellen.

. Wählen Sie basierend auf den angezeigten Laufwerkeigenschaften die Laufwerke aus, die Sie in der Volume-Gruppe verwenden möchten, und klicken Sie dann auf *Erstellen*.


Die angezeigten Laufwerkeigenschaften hängen davon ab, ob Sie die automatische oder die manuelle Methode ausgewählt haben. Weitere Informationen finden Sie in der Dokumentation zum SANtricity System Manager https://docs.netapp.com/us-en/e-series-santricity/sm-storage/create-volume-group.html["Erstellen einer Volume-Gruppe"^].
