---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-manage-software-repository.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Sie können ein Software-Repository anzeigen und managen, in dem alle Softwaredateien aufgelistet sind, die mit dem Storage Plug-in für vCenter verknüpft sind. 
---
= Managen Sie das Software Repository im SANtricity Storage Plug-in für vCenter
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können ein Software-Repository anzeigen und managen, in dem alle Softwaredateien aufgelistet sind, die mit dem Storage Plug-in für vCenter verknüpft sind.

.Bevor Sie beginnen
Wenn Sie das Repository zum Hinzufügen von SANtricity OS-Dateien verwenden, stellen Sie sicher, dass die Betriebssystemdateien auf Ihrem lokalen System verfügbar sind.

.Über diese Aufgabe
Sie können die Option SANtricity OS Software Repository verwalten verwenden, um eine oder mehrere Betriebssystemdateien auf das Hostsystem zu importieren, auf dem das Plugin ausgeführt wird. Sie können auch wählen, ob Sie eine oder mehrere Betriebssystemdateien löschen möchten, die im Software-Repository verfügbar sind.

.Schritte
. Wählen Sie in der Hauptansicht *Verwalten* und dann Menü:SANtricity-Software-Repository verwalten].
+
Das Dialogfeld SANtricity OS Software-Repository verwalten wird angezeigt.

. Führen Sie eine der folgenden Aktionen aus:
+
** *Import:*
+
... Klicken Sie Auf *Import*.
... Klicken Sie auf *Durchsuchen* und navigieren Sie dann zu dem Speicherort, an dem die Betriebssystemdateien gespeichert werden sollen. Betriebssystemdateien haben einen ähnlichen Dateinamen wie `N2800-830000-000.dlp`.
... Wählen Sie eine oder mehrere Betriebssystemdateien aus, die Sie hinzufügen möchten, und klicken Sie dann auf *Import*.


** *Löschen:*
+
... Wählen Sie eine oder mehrere Betriebssystemdateien aus, die Sie aus dem Software-Repository entfernen möchten.
... Klicken Sie Auf *Löschen*.






.Ergebnis
Wenn Sie den Import ausgewählt haben, werden die Dateien hochgeladen und validiert. Wenn Sie „Löschen“ ausgewählt haben, werden die Dateien aus dem Software-Repository entfernt.
