---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-storage-array-passwords.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Aktualisieren Sie die Passwörter, die für die Anzeige und den Zugriff auf Speicher-Arrays im Storage Plug-in für vCenter verwendet werden. 
---
= Ändern Sie die Passwörter für das Speicherarray
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können die Passwörter aktualisieren, die für die Anzeige und den Zugriff auf Speicher-Arrays im Storage Plug-in für vCenter verwendet werden.

Sie müssen das aktuelle Passwort für das Speicher-Array kennen, das in System Manager festgelegt ist.

In dieser Aufgabe geben Sie das aktuelle Passwort für ein Speicher-Array ein, damit Sie im Plugin darauf zugreifen können. Dies kann erforderlich sein, wenn das Array-Passwort in System Manager geändert wurde.

.Schritte
. Wählen Sie auf der Seite *Verwalten* ein oder mehrere Speicher-Arrays aus.
. Menü wählen:Sonstige Aufgaben[Passwörter für Speicherarrays angeben].
. Geben Sie für jedes Speicherarray das Kennwort oder die Passwörter ein, und klicken Sie dann auf *Speichern*.

