---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-delete-trusted-certificates.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Löschen Sie ein oder mehrere nicht mehr benötigte Zertifikate. 
---
= Löschen Sie vertrauenswürdige Zertifikate im SANtricity Speicher-Plugin für vCenter
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können ein oder mehrere nicht mehr benötigte Zertifikate löschen, z. B. ein abgelaufenes Zertifikat.

.Bevor Sie beginnen
Importieren Sie das neue Zertifikat, bevor Sie das alte löschen.


CAUTION: Beachten Sie, dass das Löschen eines Root- oder Zwischenzertifikats mehrere Speicher-Arrays beeinflussen kann, da diese Arrays dieselben Zertifikatdateien gemeinsam nutzen können.

.Schritte
. Wählen Sie *Zertifikatverwaltung*.
. Wählen Sie die Registerkarte * Trusted* aus.
. Wählen Sie ein oder mehrere Zertifikate in der Tabelle aus, und klicken Sie dann auf *Löschen*.
+

NOTE: Die Löschfunktion ist für vorinstallierte Zertifikate nicht verfügbar.

+
Das Dialogfeld Vertrauenswürdiges Zertifikat bestätigen wird geöffnet.

. Bestätigen Sie den Löschvorgang, und klicken Sie dann auf *Löschen*.
+
Das Zertifikat wird aus der Tabelle entfernt.


