---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-change-configuration-settings-for-a-volume-group.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Bearbeiten Sie die Einstellungen für eine Volume-Gruppe, einschließlich ihres Namens und ihres RAID-Levels. 
---
= Ändern Sie die Konfigurationseinstellungen für eine Volume-Gruppe
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Sie können die Einstellungen für eine Volume-Gruppe einschließlich Name und RAID-Level bearbeiten.

.Bevor Sie beginnen
Wenn Sie die RAID-Ebene ändern, um die Performance-Anforderungen der Applikationen, die auf die Volume-Gruppe zugreifen, zu erfüllen, müssen Sie die folgenden Voraussetzungen erfüllen:

* Die Volume-Gruppe muss den optimalen Status haben.
* Sie müssen über genügend Kapazität in der Volume-Gruppe verfügen, um auf das neue RAID-Level zu konvertieren.


.Schritte
. Wählen Sie auf der Seite Verwalten das Speicher-Array mit der Volume-Gruppe aus.
. Wählen Sie Menü:Provisioning[Pools und Volume-Gruppen konfigurieren].
. Wählen Sie die Volume-Gruppe aus, die Sie bearbeiten möchten, und klicken Sie dann auf *Einstellungen anzeigen/bearbeiten*.
+
Das Dialogfeld Volume Group Settings wird angezeigt.

. Wählen Sie die Registerkarte *Einstellungen* aus, und bearbeiten Sie anschließend die Einstellungen für die Volume-Gruppe.
+
.Felddetails
[%collapsible]
====
[cols="25h,~"]
|===
| Einstellung | Beschreibung 


 a| 
Name
 a| 
Sie können den vom Benutzer bereitgestellten Namen der Volume-Gruppe ändern. Die Angabe eines Namens für eine Volume-Gruppe ist erforderlich.



 a| 
RAID-Level
 a| 
Wählen Sie den neuen RAID-Level aus dem Dropdown-Menü aus.

** *RAID 0 Striping* -- bietet eine hohe Leistung, aber keine Datenredundanz. Wenn ein einzelnes Laufwerk in der Volume-Gruppe ausfällt, fallen alle zugehörigen Volumes aus und alle Daten gehen verloren. Eine Striping-RAID-Gruppe fasst zwei oder mehr Laufwerke zu einem großen logischen Laufwerk zusammen.
** *RAID 1 Mirroring* -- bietet eine hohe Leistung und beste Datenverfügbarkeit und eignet sich zur Speicherung sensibler Daten auf Unternehmens- oder Persönlichkeitsebene. Schützt Ihre Daten, indem der Inhalt eines Laufwerks automatisch auf das zweite Laufwerk im gespiegelten Paar gespiegelt wird. Er bietet Schutz bei Ausfall eines einzigen Laufwerks.
** *RAID 10 Striping/Spiegelung* -- bietet eine Kombination aus RAID 0 (Striping) und RAID 1 (Spiegelung) und wird erreicht, wenn vier oder mehr Laufwerke ausgewählt werden. RAID 10 ist für Transaktionsapplikationen mit hohem Volumen, z. B. für eine Datenbank mit hohen Performance- und Fehlertoleranz, geeignet.
** *RAID 5* -- optimal für Umgebungen mit mehreren Benutzern (wie Datenbank- oder Dateisystemspeicher), in denen die typische I/O-Größe klein ist und ein hoher Anteil an Leseaktivitäten besteht.
** *RAID 6* - optimal für Umgebungen, die einen Redundanzschutz über RAID 5 hinaus benötigen, jedoch keine hohe Schreib-Performance erfordern. RAID 3 kann nur Volume-Gruppen über die Befehlszeilenschnittstelle (CLI) zugewiesen werden. Wenn Sie den RAID-Level ändern, können Sie diesen Vorgang nach seinem Start nicht mehr abbrechen. Während der Änderung bleiben Ihre Daten verfügbar.




 a| 
Optimierungskapazität (nur EF600 Arrays)
 a| 
Wenn eine Volume-Gruppe erstellt wird, wird eine empfohlene Optimierungskapazität generiert, die ein Gleichgewicht zwischen der verfügbaren Kapazität und Performance sowie dem Verschleiß von Laufwerken bietet. Sie können diese Balance anpassen, indem Sie den Schieberegler nach rechts bewegen, um eine bessere Performance zu erzielen und den Verschleiß zu erhöhen. Wenn Sie die verfügbare Kapazität in die linke Seite verschieben, können Sie die verfügbare Kapazität auf Kosten einer besseren Performance und eines höheren Verschleißes der Laufwerke erhöhen. SSD-Laufwerke haben eine längere Lebensdauer und eine bessere maximale Schreib-Performance, wenn ein Teil ihrer Kapazität nicht zugewiesen ist. Bei Laufwerken, die einer Volume-Gruppe zugeordnet sind, besteht die nicht zugewiesene Kapazität aus der freien Kapazität einer Gruppe (nicht von Volumes genutzte Kapazität) und einem Teil der nutzbaren Kapazität, der als zusätzliche Optimierungskapazität zur Verfügung steht. Die zusätzliche Optimierungskapazität stellt ein Mindestmaß an Optimierungskapazität zur Verfügung, indem die nutzbare Kapazität reduziert wird. Somit ist für die Volume-Erstellung nicht verfügbar.

|===
====
. Klicken Sie Auf *Speichern*.


Wenn die Kapazität reduziert wird, die Volume-Redundanz verloren geht oder der Schutz vor Shelf-/Schubladenverlust infolge einer Änderung auf RAID-Ebene verloren geht, wird ein Bestätigungsdialogfeld mit dem Kunden angezeigt. Wählen Sie *Ja*, um fortzufahren. Klicken Sie andernfalls auf *Nein*.

.Ergebnis
Wenn Sie den RAID-Level für eine Volume-Gruppe ändern, ändert das Plugin die RAID-Level jedes Volumes, das die Volume-Gruppe enthält. Die Leistung kann während des Betriebs leicht beeinträchtigt werden.
