---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-import-alert-settings.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Importieren von Alarmkonfigurationen aus einem Speicher-Array in andere Speicher-Arrays. 
---
= Warnungseinstellungen importieren
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Sie können Alarmkonfigurationen von einem Speicher-Array in andere Speicher-Arrays importieren. Dieser Batch-Betrieb spart Zeit, wenn Sie mehrere Arrays im Netzwerk konfigurieren müssen.

.Bevor Sie beginnen
Stellen Sie sicher, dass:

* Warnmeldungen werden in System Manager (Menü:Einstellungen[Warnungen]) für das Speicherarray konfiguriert, das als Quelle verwendet werden soll.
* Die vorhandene Konfiguration für die Ziel-Speicher-Arrays wird in System Manager gesichert (Menü:Einstellungen[System > Speicherarray-Konfiguration speichern]).
* Sie haben die Anforderungen für die Replizierung von Speicherkonfigurationen in überprüft link:vc-olh-import-settings-overview.html["Überblick über die Einstellungen importieren"].


.Über diese Aufgabe
Sie können E-Mail-, SNMP- oder Syslog-Warnungen für den Importvorgang auswählen:

* *E-Mail-Benachrichtigungen* -- Eine E-Mail-Server-Adresse und die E-Mail-Adressen der Alarmempfänger.
* *Syslog Alerts* -- Eine Syslog-Serveradresse und ein UDP-Port.
* *SNMP Alerts* -- Ein Community-Name und IP-Adresse für den SNMP-Server.


.Schritte
. Klicken Sie auf der Seite Verwalten auf Menü:Aktionen[Einstellungen importieren].
+
Der Assistent für Importeinstellungen wird geöffnet.

. Wählen Sie im Dialogfeld Einstellungen auswählen entweder *E-Mail-Alarme*, *SNMP-Alarme* oder *Syslog-Warnungen* aus und klicken Sie dann auf *Weiter*.
+
Zum Auswählen des Quell-Arrays wird ein Dialogfeld geöffnet.

. Wählen Sie im Dialogfeld Quelle auswählen das Array mit den zu importierenden Einstellungen aus, und klicken Sie dann auf *Weiter*.
. Wählen Sie im Dialogfeld Ziele auswählen ein oder mehrere Arrays aus, um die neuen Einstellungen zu erhalten.
+

NOTE: Speicher-Arrays mit Firmware unter 8.50 stehen nicht zur Auswahl. Darüber hinaus wird in diesem Dialogfeld kein Array angezeigt, wenn das Plug-in nicht mit diesem Array kommunizieren kann (z. B. wenn es offline ist oder wenn es Probleme mit Zertifikat, Kennwort oder Netzwerk hat).

. Klicken Sie Auf *Fertig Stellen*.
+
Auf der Seite Operationen werden die Ergebnisse des Importvorgangs angezeigt. Wenn der Vorgang fehlschlägt, können Sie auf die Zeile klicken, um weitere Informationen anzuzeigen.



.Ergebnis
Die Ziel-Storage-Arrays sind jetzt so konfiguriert, dass sie Warnmeldungen per E-Mail, SNMP oder Syslog an Administratoren senden.
