---
sidebar: sidebar 
permalink: vcenter-plugin/vc-olh-turn-on-locator-lights.html 
keywords: vCenter plugin, Plugin for vCenter, SANtricity plugin for vCenter 
summary: Nach Laufwerken können Sie alle Laufwerke physisch identifizieren, die einen ausgewählten Pool, eine Volume-Gruppe oder SSD Cache umfassen. An jedem Laufwerk im ausgewählten Pool, der Volume-Gruppe oder dem SSD-Cache leuchtet eine LED-Anzeige auf. 
---
= Schalten Sie die LED-Anzeigen auf einem Laufwerk im SANtricity-Speichermodul für vCenter ein
:hardbreaks:
:allow-uri-read: 
:experimental: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Nach Laufwerken können Sie alle Laufwerke physisch identifizieren, die einen ausgewählten Pool, eine Volume-Gruppe oder SSD Cache umfassen. An jedem Laufwerk im ausgewählten Pool, der Volume-Gruppe oder dem SSD-Cache leuchtet eine LED-Anzeige auf.

.Schritte
. Wählen Sie auf der Seite Verwalten das Speicher-Array aus.
. Wählen Sie Menü:Provisioning[Pools und Volume-Gruppen konfigurieren].
. Wählen Sie den Pool, die Volume-Gruppe oder den SSD-Cache aus, den Sie suchen möchten, und klicken Sie dann auf MENU:Mehr[Locator Lights einschalten].
+
Es wird ein Dialogfeld angezeigt, in dem die Leuchten der Laufwerke angezeigt werden, die den ausgewählten Pool, die Volume-Gruppe oder den SSD-Cache enthalten.

. Nachdem Sie die Laufwerke erfolgreich gefunden haben, klicken Sie auf *Ausschalten*.

