---
permalink: maintenance-e5700/batteries-intro-concept.html 
sidebar: sidebar 
keywords: E5700 battery, repair E5700 battery, replace E5700 battery, failed E5700 battery 
summary: Anforderungen und Überlegungen zum Austausch von E5700 Batterien prüfen 
---
= Voraussetzungen für den Austausch der Batterie – E5700
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie eine E5700 Batterie ersetzen, lesen Sie bitte die Anforderungen und Überlegungen.

Jeder Controller-Behälter enthält eine Batterie, die zwischengespeicherte Daten behält, wenn die Wechselstromversorgung ausfällt.



== Recovery Guru – Warnmeldungen

Wenn der Recovery Guru in SANtricity System Manager einen der folgenden Statusmeldungen meldet, müssen Sie die betroffene Batterie austauschen:

* Akku Defekt
* Austausch Der Batterie Erforderlich


Sehen Sie sich im SANtricity System Manager die Details im Recovery Guru an, um zu überprüfen, ob ein Problem mit einer Batterie vorliegt, und um sicherzustellen, dass keine weiteren Punkte zuerst behoben werden müssen.



== Verfahrensübersicht

Um Ihre Daten zu schützen, müssen Sie eine fehlerhafte Batterie so schnell wie möglich austauschen.

Im Folgenden finden Sie eine Übersicht über die Schritte zum Austauschen einer Batterie in E5700 Controllern (E5724, EF570 oder E5760):

. Controller in den Offline-Modus versetzen (nur Duplex).
. Den Controller-Behälter ausbauen.
. Tauschen Sie die Batterie aus.
. Den Controller-Behälter austauschen.
. Stellen Sie den Controller online (nur Duplex).




== Anforderungen

Wenn Sie einen fehlerhaften Akku austauschen möchten, müssen Sie Folgendes haben:

* Eine Ersatzbatterie.
* Ein ESD-Armband, oder Sie haben andere antistatische Vorsichtsmaßnahmen getroffen.
* Etiketten, um jedes Kabel zu identifizieren, das mit dem Controller-Behälter verbunden ist.
* Eine Management Station mit einem Browser, der für den Controller auf den SANtricity System Manager zugreifen kann. (Zeigen Sie zum Öffnen der System Manager-Schnittstelle den Domain-Namen oder die IP-Adresse des Controllers im Browser.)
+
Optional können Sie einige der Verfahren mit der Befehlszeilenschnittstelle (CLI) ausführen. Wenn Sie keinen Zugriff auf die CLI haben, können Sie einen der folgenden Aktionen ausführen:

+
** *Für SANtricity System Manager (Version 11.60 und höher)* -- Laden Sie das CLI-Paket (ZIP-Datei) aus dem System Manager herunter. Wechseln Sie zum Menü:Einstellungen[System > Add-ons > Command Line Interface]. Sie können dann CLI-Befehle von einer Betriebssystemaufforderung ausgeben, z. B. von der DOS C:-Eingabeaufforderung.
** *Für SANtricity Storage Manager/Enterprise Management Window (EMW)* -- Folgen Sie den Anweisungen im Express Guide, um die Software herunterzuladen und zu installieren. Sie können CLI-Befehle über EMW ausführen, indem Sie Menü:Extras[Skript ausführen] auswählen.



