---
permalink: maintenance-e5700/hics-overview-supertask-concept.html 
sidebar: sidebar 
keywords: E5700 host interface card, E5700 HIC, replace E5700 HIC, failed E5700 HIC 
summary: Anforderungen für den Austausch der E5700 HIC prüfen 
---
= Voraussetzung für den Austausch der Host-Schnittstellenkarte (HIC) – E5700
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Prüfen Sie die Anforderungen und Überlegungen, bevor Sie eine Host-Schnittstellenkarte (HIC) in einer E5700 hinzufügen, aktualisieren oder ersetzen.



== Verfahrensübersicht

Sie können eine HIC im E5724 Controller Shelf und im E5760 Controller-Shelf hinzufügen, aktualisieren oder ersetzen.

Im Folgenden finden Sie eine Übersicht über die Schritte zum Ersetzen einer HIC in einem E5700 Controller (E5724 oder E5760):

. Versetzen Sie den Controller in den Offline-Modus
. Den Controller-Behälter ausbauen
. Tauschen Sie die Batterie aus
. Den Controller-Behälter austauschen
. Versetzen Sie den Controller in den Online-Modus




== Anforderungen für das Hinzufügen, Aktualisieren oder Ersetzen einer HIC

Wenn Sie eine Host Interface Card (HIC) hinzufügen, aktualisieren oder ersetzen möchten, beachten Sie bitte die folgenden Anforderungen.

* Sie müssen für dieses Verfahren ein Wartungsfenster zur Ausfallzeit planen. Die Stromversorgung muss ausgeschaltet sein, wenn Sie HICs installieren. Daher können Sie erst dann auf Daten im Speicher-Array zugreifen, wenn Sie diesen Vorgang erfolgreich abgeschlossen haben. (In einer Duplexkonfiguration liegt dies daran, dass beide Controller beim Einschalten dieselbe HIC-Konfiguration haben müssen.)
* Sie benötigen zwei HICs, die mit Ihren Controllern kompatibel sind.
+
Bei Duplexkonfigurationen (zwei Controller) müssen die HICs, die in den beiden Controller-Kanistern installiert sind, identisch sein. Wenn nicht übereinstimmende HIC vorhanden sind, wird der Controller mit der Ersatz-HIC gesperrt, wenn Sie ihn online schalten.

* Für die Verbindung der neuen Host-Ports sind alle Kabel, Transceiver, Switches und Host Bus Adapter (HBAs) erforderlich.
+
Informationen über kompatible Hardware finden Sie im https://mysupport.netapp.com/NOW/products/interoperability["NetApp Interoperabilitätsmatrix"^] Oder im http://hwu.netapp.com/home.aspx["NetApp Hardware Universe"^].

* Sie haben ein ESD-Armband oder andere antistatische Vorsichtsmaßnahmen getroffen.
* Sie haben einen #1 Kreuzschlitzschraubendreher.
* Sie haben Etiketten, um jedes Kabel zu identifizieren, das mit dem Controller-Behälter verbunden ist.
* Sie verfügen über eine Management Station mit einem Browser, der für den Controller auf den SANtricity System Manager zugreifen kann. (Zeigen Sie zum Öffnen der System Manager-Schnittstelle den Domain-Namen oder die IP-Adresse des Controllers im Browser.)

