---
permalink: maintenance-e5700/index.html 
sidebar: sidebar 
keywords: E5700 maintenance, repair E5700, replace E5700 components, E5724, EF570, E5760 
summary: Instandhaltung der E5700 Hardware 
---
= Wartung von E5700 Hardware
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Möglicherweise müssen Sie Wartungsverfahren für Ihre Hardware durchführen. In diesem Abschnitt werden spezifische Verfahren zur Wartung der E5700 Systemkomponenten beschrieben.

Bei den in diesem Abschnitt beschriebenen Verfahren wird vorausgesetzt, dass das E5700 System bereits in der E-Series Umgebung implementiert wurde.



== Systemkomponenten

Für das E5700 Storage-System können Sie Wartungsvorgänge für die folgenden Komponenten durchführen.

[cols="25,65"]
|===


 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/batteries-intro-concept.html["Batterien"]
 a| 
Ein Akku ist im Lieferumfang eines Controller-Kanisters enthalten und behält die Daten im Cache bei Ausfall der Wechselstromversorgung bei.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/controllers-overview-concept.html["Controller"]
 a| 
Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Sie steuert die Laufwerke und implementiert die Funktionen von System Manager.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/canisters-overview-supertask-concept.html["Kanister"]
 a| 
Behälter bestehen aus drei verschiedenen Typen: Stromverlüfter (Netzteile), die eine redundante Stromversorgung und eine ausreichende Kühlung in einem Controller-Shelf mit 12 Laufwerken oder 24 Laufwerken bereitstellen. Stromversorgungs-Behälter, die für Redundanz in einem Controller-Shelf für 60 Laufwerke oder Festplatten-Shelf verwendet werden. Und Lüfter-Kanister, die zum Kühlen des Controller-Shelfs für 60 Laufwerke oder des Laufwerks-Shelfs verwendet werden.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/drives-overview-supertask-concept.html["Laufwerke"]
 a| 
Ein Laufwerk ist ein elektromagnetisches mechanisches Gerät, das die physischen Speichermedien für Daten zur Verfügung stellt.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/hics-overview-supertask-concept.html["Host-Schnittstellenkarten (HICs)"]
 a| 
Eine Host Interface Card (HIC) kann optional in einem Controller-Behälter installiert werden. Der E5700 Controller enthält integrierte Host-Ports auf der Controller-Karte selbst sowie Host-Ports auf der optionalen HIC. Host Ports, die in den Controller integriert sind, werden als Baseboard Host Ports bezeichnet. In die HIC integrierte Host Ports werden HIC Ports genannt.



 a| 
https://docs.netapp.com/us-en/e-series/maintenance-e5700/hpp-overview-supertask-concept.html["Host-Port-Protokoll"]
 a| 
Sie können das Host-Protokoll in ein anderes Protokoll umwandeln, um Kompatibilität und Kommunikation herzustellen.

|===