---
permalink: maintenance-ef50-ef80/io-module-overview.html 
sidebar: sidebar 
keywords: ef50, ef80, replace io module, upgrade io module, io module overview 
summary: Die Speichersysteme EF50 und EF80 bieten Flexibilität beim Austausch oder bei der Aufrüstung von E/A-Modulen, um die Netzwerkverbindung und Leistung zu verbessern und die Speicherkapazität zu erhöhen. 
---
= Informationen zur Wartung von E/A-Modulen für EF50 und EF80 Speichersysteme
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Speichersysteme EF50 und EF80 bieten Flexibilität beim Austausch oder bei der Aufrüstung von E/A-Modulen, um die Netzwerkverbindung und Leistung zu verbessern und die Speicherkapazität zu erhöhen.

* link:io-module-replace.html["Ersetzen Sie ein I/O-Modul"]
+
Wenn ein E/A-Modul in Ihrem Speichersystem ausfällt, können Sie es durch ein E/A-Modul desselben Typs ersetzen, um das Speichersystem wieder in seinen optimalen Betriebszustand zu versetzen.

* link:io-module-upgrade.html["Upgrade eines I/O-Moduls"]
+
Die E/A-Module Ihres Speichersystems können aufgerüstet werden, um die Anzahl der Host-Ports für eine verbesserte Netzwerkanbindung zu erhöhen, die Fähigkeit Ihres Systems zur Verarbeitung von Datenverkehr zu erweitern und SAS-Erweiterungsgehäuse anzuschließen.

+

NOTE: SAS Erweiterungs-E/A-Module werden auf Speichersystemen unterstützt, auf denen SANtricity 12.10 oder höher ausgeführt wird.


