---
permalink: maintenance-ef600/controllers-overview-supertask-concept.html 
sidebar: sidebar 
keywords: replace controller, EF300, EF600, EF300C, EF600C 
summary: Anforderungen und Überlegungen für den Austausch des EF300- oder EF600 Controllers 
---
= Voraussetzung für den Austausch des Controllers – EF300 oder EF600
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Bevor Sie ein EF300, EF600 ersetzen. EF300C oder EF600C-Controller, überprüfen Sie die Anforderungen und Überlegungen.

Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Sie steuert die Laufwerke und implementiert die Funktionen des SANtricity-System-Managers.



== Anforderungen für den Austausch des Controllers

Bevor Sie einen Controller austauschen, müssen folgende Funktionen erforderlich sein:

* Ein Ersatzcontroller-Behälter mit der gleichen Teilenummer wie der Controller-Behälter, den Sie austauschen.
* Ein ESD-Armband, oder Sie haben andere antistatische Vorsichtsmaßnahmen getroffen.
* Etiketten, um jedes Kabel zu identifizieren, das mit dem Controller-Behälter verbunden ist.
* A #1 Kreuzschlitzschraubendreher.
* Eine Management Station mit einem Browser, der für den Controller auf den SANtricity System Manager zugreifen kann. (Zeigen Sie zum Öffnen der System Manager-Schnittstelle den Domain-Namen oder die IP-Adresse des Controllers im Browser.)




== Ersatz beim Einschalten

Sie können einen Controller-Behälter ersetzen, während Ihr Speicher-Array eingeschaltet ist und Host-I/O-Vorgänge ausführt, wenn die folgenden Bedingungen erfüllt sind:

* Der zweite Reglerbehälter im Regal hat optimalen Status.
* Im Feld *OK to remove* im Bereich Details des Recovery Guru im SANtricity System Manager wird *Ja* angezeigt, was darauf hinweist, dass es sicher ist, diese Komponente zu entfernen.

