---
permalink: maintenance-ef600/hics-overview-supertask-concept.html 
sidebar: sidebar 
keywords: EF300, EF600, EF300C, EF600C, replace HIC, replace HIC, host interface card failed, HIC failure 
summary: Prüfen Sie die Anforderungen und Überlegungen, bevor Sie eine EF300- oder EF600-HIC ersetzen. 
---
= Voraussetzungen für das Upgrade der Host-Schnittstellenkarte (HIC) - EF300 oder EF600
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Lesen Sie vor dem Upgrade oder Austausch einer Host-Schnittstellenkarte (HIC) in einem EF300-, EF600-, EF300C- oder EF600C-Array die folgenden Anforderungen durch.

* Sie haben für dieses Verfahren ein Zeitfenster für die Wartung von Ausfallzeiten eingeplant. Sie können erst nach erfolgreichem Abschluss dieses Verfahrens auf Daten im Speicher-Array zugreifen. Da beide Controller beim Einschalten die gleiche HIC-Konfiguration haben müssen, muss der Strom beim Ändern der HIC-Konfiguration ausgeschaltet sein. Wenn nicht übereinstimmende HIC vorhanden sind, wird der Controller mit der Ersatz-HIC gesperrt, wenn Sie ihn online schalten.
* Für die Verbindung der neuen Host-Ports sind alle Kabel, Transceiver, Switches und Host Bus Adapter (HBAs) erforderlich.
+
Informationen über kompatible Hardware finden Sie im https://mysupport.netapp.com/NOW/products/interoperability["NetApp Interoperabilitätsmatrix"^] Oder im http://hwu.netapp.com/home.aspx["NetApp Hardware Universe"^].

* Sie haben ein ESD-Armband oder andere antistatische Vorsichtsmaßnahmen getroffen.
* Sie haben einen #1 Kreuzschlitzschraubendreher.
* Sie haben Etiketten, um jedes Kabel zu identifizieren, das mit dem Controller-Behälter verbunden ist.
* Eine Management Station mit einem Browser, der für den Controller auf den SANtricity System Manager zugreifen kann. (Zeigen Sie zum Öffnen der System Manager-Schnittstelle den Domain-Namen oder die IP-Adresse des Controllers im Browser.)
* Bei einigen HIC-Ersetzungen oder Upgrades ist möglicherweise ein Host Port-Protokoll erforderlich. Befolgen Sie die Anweisungen im xref:hpp-change-supertask-task.html[Ändern des Host-Protokolls für eine EF300 oder EF600] Für diese Anforderung.
* Für EF300-Controller muss HIC Port 2 mit einer HIC für Host-Konnektivität gefüllt sein.

