---
permalink: config-windows/verify-windows-config-support-task.html 
sidebar: sidebar 
keywords: express Windows configuration, software configuration, Windows host, E2800, E5700, EF300, EF600, E-Series, eseries 
summary: Vergewissern Sie sich, dass die Windows-Konfiguration unterstützt wird. 
---
= Überprüfen Sie, ob die Windows-Konfiguration unterstützt wird
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Um einen zuverlässigen Betrieb zu gewährleisten, erstellen Sie einen Implementierungsplan und überprüfen Sie mit dem NetApp Interoperabilitäts-Matrix-Tool (IMT), ob die gesamte Konfiguration unterstützt wird.

.Schritte
. Wechseln Sie zum http://mysupport.netapp.com/matrix["NetApp Interoperabilitäts-Matrix-Tool"^].
. Klicken Sie auf die Kachel * Storage Solution Search*.
. Klicken Sie im Menü:Protokolle[SAN Host] auf die Schaltfläche *Hinzufügen* neben *E-Series SAN-Host*.
. Klicken Sie Auf *Suchkriterien Verfeinern*.
+
Der Abschnitt Suchkriterien verfeinern wird angezeigt. In diesem Abschnitt können Sie das zutreffende Protokoll sowie andere Kriterien für die Konfiguration auswählen, z. B. Betriebssystem, NetApp OS und Host Multipath-Treiber. Wählen Sie die Kriterien aus, die Sie für Ihre Konfiguration kennen, und sehen Sie dann, welche kompatiblen Konfigurationselemente gelten. Führen Sie bei Bedarf die Updates für Ihr Betriebssystem und Protokoll durch, die im Tool vorgeschrieben sind. Detaillierte Informationen zu der von Ihnen gewählten Konfiguration finden Sie auf der Seite Unterstützte Konfigurationen anzeigen, indem Sie auf den rechten Seitenpfeil klicken.

. Nehmen Sie bei Bedarf die in der Tabelle aufgeführten Aktualisierungen für Ihr Betriebssystem und Protokoll vor.
+
|===
| Betriebssystem-Updates | Protokoll | Protokollbezogene Updates 


 a| 
Möglicherweise müssen Sie Out-of-Box-Treiber installieren, um die Funktionalität und den Support zu gewährleisten.

Jeder HBA-Anbieter verfügt über spezifische Methoden zur Aktualisierung des Boot-Codes und der Firmware. Im Support-Abschnitt auf der Website des Anbieters finden Sie die Anweisungen und Software, die zur Aktualisierung des HBA-Startcodes und der Firmware erforderlich sind.
 a| 
FC
 a| 
Host Bus Adapter (HBA)-Treiber, Firmware und Bootcode



 a| 
ISCSI
 a| 
NIC-Treiber (Network Interface Card), Firmware und Bootcode.



 a| 
SAS
 a| 
Host Bus Adapter (HBA)-Treiber, Firmware und Bootcode

|===

