---
permalink: upgrade-controllers/index.html 
sidebar: sidebar 
keywords: E-Series, eseries, E4000, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, upgrade controller, upgrade DIMMs 
summary: Überblick über das Upgrade eines E-Series Arrays durch den Austausch von Controllern 
---
= Controller-Upgrade – Übersicht
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Sie können ein Upgrade Ihres Storage-Arrays durch den Austausch vorhandener Controller durchführen.



== Controller-Komponenten

Ein Controller besteht aus einer Hauptplatine, Firmware und Software. Sie steuert die Laufwerke und implementiert auch die Management Software-Funktionen.



== Wann wird dieses Verfahren durchgeführt

In der Regel verwenden Sie diese Vorgehensweise, wenn Sie alle Controller auf ein anderes Modell oder eine andere Plattform aktualisieren möchten. Bei diesem Verfahren werden alle Controller in einem Controller-Laufwerksfach ausgetauscht

Sie können dieses Verfahren auch in folgenden Situationen verwenden:

* Wenn bei allen Controllern in einem Controller-Laufwerksfach ein Hardwarefehler auftreten und nicht mehr funktionsfähig ist.
* Um die zwei Inline-Speichermodule (DIMMs) in der Controller-Laufwerksfach zu aktualisieren, indem beide Controller durch dasselbe Controller-Modell ersetzt werden, jedoch durch unterschiedliche DIMMs.



NOTE: Die HIC-Upgrade-Szenarien werden in diesem Verfahren nicht behandelt. Weitere Informationen finden Sie im HIC Verfahren zum Hinzufügen, Aktualisieren und Austauschen Ihres E-Series Systems.
