---
permalink: upgrade-controllers/reconfigure-sas-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, reconfigure SAS-2, SAS-2, SAS-3, convert controller shelf, convert drive shelf, 
summary: 'Sie können das Controller-Shelf in ein genehmigtes SAS-2 Array (E2700, E550/EF5500, E5600/EF560) in ein Festplatten-Shelf konvertieren und dann das Shelf mit allen zugehörigen genehmigten SAS-2 Laufwerk-Shelfs (DE1600, DE5600, DE6600) hinter einem neu genehmigten SAS-3 Array (E2800, E5700/EF570) und genehmigten SAS-3 Laufwerk-Shelfs (DE212C, DE224C, DE460C) platzieren. Ohne Datenhaltung.' 
---
= Konfigurieren Sie ein SAS-2-System hinter einem neuen SAS-3 Controller-Shelf neu
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Falls erforderlich können Sie Ihr SAS-2-System neu konfigurieren, damit Sie es hinter einem neuen SAS-3-Controller-Shelf verwenden können.

Zu den genehmigten SAS-2 Arrays gehören die E2700, E550/EF5500 und die E5600/EF560. Genehmigte SAS-2-Festplatten-Shelfs umfassen DE1600, DE5600 und DE6600. Zu den genehmigten SAS-3 Arrays gehören die E2800 und E5700/EF570. Genehmigte SAS-3 Laufwerk-Shelfs umfassen DE212C, DE224C und DE460C.

.Über diese Aufgabe
Bei diesem Verfahren konvertieren Sie das Controller-Shelf in ein genehmigtes SAS-2 Array in ein Festplatten-Shelf und legen dieses Shelf anschließend ohne Erhalt der Daten hinter ein neu genehmigtes SAS-3 Array und Laufwerk-Shelfs.

Dieses Verfahren gilt für die IOM12- und IOM12B-Laufwerkseinschübe.


NOTE: IOM12B-Module werden nur ab SANtricity OS 11.07.2 unterstützt. Stellen Sie sicher, dass die Firmware Ihres Controllers aktualisiert wurde, bevor Sie auf ein IOM12B installieren oder aktualisieren.

.Bevor Sie beginnen
Aufgrund der Komplexität dieses Verfahrens ist Folgendes erforderlich:

* Sie benötigen eine FPVR (Feature Product Variance Request). Wenden Sie sich an NetApp Professional Services, wenn Sie eine FPVR-Datei erstellen möchten.
+

NOTE: Wird ein FPVR nicht erfasst, bevor dieser Vorgang durchgeführt wird, kann dies zu einem Laufwerksausfall und einer Controller-Sperre führen.

* Wenn Sie Ihre Daten sichern können, führen Sie dieses Verfahren ohne Unterstützung durch die NetApp Professional Services durch.
* Wenn Sie kein Backup Ihrer Daten erstellen können, wenden Sie sich zur Unterstützung bei diesem Verfahren an die NetApp Professional Services.
* Stellen Sie sicher, dass beide Arrays für das Verfahren vorbereitet sind:
+
** *Vorhandenes Array*: Vorhandenes Array mit SANtricity OS 8.25 oder höher, das eingeschaltet wird.
** *Neues Array*: Neues Array entpackt und abgeschaltet.


* Notieren Sie die Seriennummer des SAS-2 Controller Shelf, das Sie in ein Festplatten-Shelf konvertieren werden.




== Schritt 1: Controller herunterfahren (Non-Data-Erhalt)

Alle Vorgänge müssen heruntergefahren werden, bevor Sie die Controller herunterfahren können.

.Schritte
. Wenn weiterhin auf das vorhandene SAS-2-Array zugegriffen werden kann, löschen Sie alle Volume-Gruppen, schalten Sie beide Controller aus und entfernen Sie alle Kabel.
. Notieren Sie die Seriennummer des SAS-2 Controller Shelf, das Sie in ein Festplatten-Shelf konvertieren werden.
. Wenn für das vorhandene Array die Laufwerksicherheit verwendet wird, stellen Sie sicher, dass der Sicherheitsschlüssel verfügbar ist.




== Schritt 2: Installation der Controller (Nichtdatenhaltung)

Nach erfolgreichem Herunterfahren können Sie die Controller im Array ersetzen.

.Schritte
. Ersetzen Sie beide Controller im vorhandenen Array durch IOMs oder ESMs.
. Verwenden Sie, falls möglich, die Hostkabel und Netzwerkkabel des vorhandenen Arrays, und verbinden Sie sie mit den Controllern im neuen Array.
+

NOTE: Je nach Host-Verbindungen Ihres neuen Arrays sind möglicherweise unterschiedliche Kabel erforderlich.

. Verkabeln Sie die Laufwerk-Shelfs hinter den Controllern im neuen Array.
+
Das vorhandene Controller-Laufwerksfach und alle angeschlossenen Laufwerksfächer werden zu Laufwerk-Shelfs und können mit den Controllern im neuen Array verbunden werden.

+

NOTE: Für den Anschluss von SAS-2 an SAS-3 sind SAS-HD-Kabel zu Mini-SAS-Kabel erforderlich. Weitere detaillierte Informationen zur Verkabelung Ihres besonderen Controllers und zur Erweiterungs-Shelf-Konfiguration finden Sie unter link:../install-hw-cabling/index.html["Verkabelung"] Oder im https://library.netapp.com/ecm/ecm_download_file/ECMLP2588749["Hardware-Verkabelungsleitfaden für die E-Series"^].





== Schritt 3: Einschalten der Controller (Nichtdatenhaltung)

Schalten Sie nach Abschluss der Installation die Controller ein und übermitteln Sie Ihre Konfigurationsänderungen an den NetApp Technical Support.

.Schritte
. Schalten Sie das neue Array einschließlich aller angeschlossenen Festplatten-Shelfs ein.
. Konfigurieren Sie den Managementport und die IP-Adressen durch Installation des https://mysupport.netapp.com/tools/info/ECMLP2563821I.html["SANtricity Quick Connect"^] Utility:
. Wenn die Laufwerksicherheit im vorhandenen Array verwendet wurde, importieren Sie den Sicherheitsschlüssel.
. Wenn Sie die Volume-Gruppen vor dem Ausführen dieses Vorgangs nicht aus Ihrem vorhandenen Array löschen konnten, müssen Sie festlegen, dass alle ausländischen Laufwerke als nativ angezeigt werden. Ausführliche Informationen zum Einstellen von Laufwerken auf native Funktionen finden Sie in der Online-Hilfe von SANtricity.
. Senden Sie Ihre Konfigurationsänderungen an den NetApp Technical Support.
+
.. Holen Sie sich die Seriennummer des alten Laufwerksfachs, das Sie in Schritt 2 aufgezeichnet haben.
.. Melden Sie sich bei an http://mysupport.netapp.com/eservice/assistant["NetApp Support Website"^].
.. Wählen Sie in der Dropdown-Liste unter *Feedbackkategorie* die Option *installierte Produkte > Decommission Request* aus.
.. Wählen Sie *Fall Erstellen*. Geben Sie den folgenden Text in das Textfeld *Kommentare* ein und ersetzen Sie die Seriennummer Ihres Controller-Laufwerksfachs für die Seriennummer:
+
`Please decommission this serial number as the entitlement has been moved to another serial number in the system. Please reference this in the SN notes.`

.. Wählen Sie *Senden*.




Die vollständigen Konfigurationsänderungen zwischen SAS-2 und SAS-3 werden beim technischen Support von NetApp eingereicht.
