---
permalink: upgrade-controllers/remount-volumes-lsi-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, remount volume, upgrade LSI, vendor ID 
summary: Sie mounten Volumes neu, wenn Ihr Controller-Upgrade dazu führt, dass die Anbieter-ID von LSI zu NETAPP geändert wird. 
---
= Volumes neu einbinden nach Anbieterwechsel von LSI zu NETAPP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Wenn Ihr Controller-Upgrade dazu führt, die Anbieter-ID von LSI zu NETAPP zu ändern, befolgen Sie das entsprechende Verfahren für Ihren Host-Typ:

*  volumes on an AIX host
*  volumes on a VMware host
*  volumes on a Windows host




== Volumes neu auf einem AIX-Host mounten

Nachdem Sie die Controller ersetzt haben, stellen Sie möglicherweise fest, dass der Host die neuen Volumes im Speicher-Array anzeigt, aber auch die ursprünglichen Volumes als fehlgeschlagen angezeigt werden.

Wenn fehlerhafte Volumes angezeigt werden, führen Sie den aus `cfgmgr` Befehl.



== Volumes neu auf einem VMware Host mounten

Nach dem Austausch der Controller haben Sie möglicherweise folgende Bedingungen:

* VMware zeigt neue Pfade für die Volumes im Storage Array, zeigt aber auch die ursprünglichen Pfade als Sackgassein.
* Die Hosts nennen weiterhin die Volumes auf dem Storage Array mit LSI Anbieter-IDs. Dies kann auftreten, wenn die Volumes zu Beginn von der LSI-Regel beansprucht wurden und so weiter die gleiche LSI-Regel verwenden, wenn die Volumes wieder online gehen.
* Der Anzeigename stellt nicht die Änderung von LSI zu NetApp dar. Dies kann auftreten, weil der Anzeigename nach der ersten Erkennung zum kostenlosen Test wurde. In diesem Fall können Sie den Anzeigenamen manuell ändern.


.Schritte
. Führen Sie auf jedem Host einen erneuten Scan durch.
. Beenden Sie alle Host-I/O-Vorgänge für dieses Subsystem.
. Gewinnen Sie die Volumes unter einer NetApp Regel zurück.
+
.. Führen Sie die aus `esxcli storage core device list` Befehl. Überprüfen Sie die Ausgabe des Befehls, um Volumes zu identifizieren, deren Namen das Formular haben `aa.xxxx`.
.. Führen Sie den Befehl aus `do esxcli storage core claiming reclaim -d naa.xxxxx` So ändern Sie die LSI-Anbieter-ID in NetApp.






== Volumes neu auf einem Windows Host mounten

Nachdem Sie die Controller ersetzt haben, müssen Sie Volumes auf einem Windows-Host neu mounten, damit verbundene Hosts I/O-Vorgänge mit den Volumes auf dem aktualisierten Speicher-Array ausführen können.

.Schritte
. Wählen Sie im *Geräte-Manager* die Option *Ausgeblendete Geräte anzeigen*.
. Klicken Sie für jedes IM *Geräte-Manager* aufgeführte NETAPP SCSI-Festplattengerät mit der rechten Maustaste auf den Eintrag und wählen Sie *Deinstallieren* aus.
+
Wenn Windows ein Dialogfeld mit einer Meldung anzeigt, dass Sie den Host neu starten sollen, beenden Sie die Deinstallation aller Volumes, bevor Sie nach Hardware suchen und neu starten.

. Klicken Sie mit der rechten Maustaste in den *Geräte-Manager*, und wählen Sie dann *nach Hardware-Änderungen suchen*.
. Starten Sie den Host neu.

