---
permalink: upgrade-controllers/upgrade-unlock-drives-task.html 
sidebar: sidebar 
keywords: E-Series, eseries, E2800, E5700, EF300, EF600, upgrade controller, upgrading controller, unlock drives, key management, Drive Security, 
summary: Wenn Sie E2800 und E5700 Controller aktualisieren und die Laufwerkssicherheitsfunktion aktiviert ist, müssen die Laufwerke manuell entsperrt werden. 
---
= Entsperren von Laufwerken
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Die Laufwerkssicherheitsfunktion für diese Controller sperrt die Laufwerke teilweise, extern oder intern. Wenn die Laufwerkssicherheitsfunktion aktiviert ist, müssen Sie diese Laufwerke manuell entsperren.

Befolgen Sie das entsprechende Verfahren für:

* <<Internes Verschlüsselungsmanagement>>
* <<Externes Verschlüsselungskeymanagement>>




== Internes Verschlüsselungsmanagement

Führen Sie diese Schritte für das interne Verschlüsselungsmanagement aus, wenn alle Laufwerke gesperrt sind.

.Über diese Aufgabe
Die neu getauschten Controller werden mit einem siebensegmentreichen Anzeigefeld von *L5* gesperrt. Diese Sperre tritt auf, wenn keine Laufwerke die Autocodierung (ACS) durchführen können. Nach dem Import des Sicherheitsschlüssels wird ACS die neuen Controller wieder aufgenommen und aktualisiert.


NOTE: Wenn Sie Management-Port 1 nicht verwenden, versuchen Sie es mit anderen Standard-IP-Adressen: + Strg A Port 1: 169.254.128.101 + Strg A Port 2: 169.254.128.102 + Strg B Port 1: 169.254.128.101 + Strg B Port 2: 169.254.128.102

.Schritte
. Stellen Sie eine direkte, private ethernet-Verbindung zwischen dem Speicher-Array und dem Laptop oder PC des SANtricity-Clients her. Dazu:
+
.. Verwenden Sie ein RJ45-ethernet-Kabel, um den Laptop mit dem Verwaltungsport 1 an Controller A zu verbinden
.. Um die Verbindung abzuschließen, müssen Sie den Laptop möglicherweise einer IP-Adresse im selben Subnetz zuweisen wie Controller A. während der Controller-Sperrung wird Controller A standardmäßig auf die Managementadresse 169.254.128.101 gesetzt. Sie können den Laptop also einem Subnetz wie „169.254.128.201“ zuweisen.


. Importieren Sie unter Verwendung der IP-Adresse 169.254.128.101 mit dem Benutzernamen *admin* und dem Passwort leer den internen Schlüssel mit dem `import storageArray securityKey file` CLI-Befehl, wobei der Sicherheitsschlüssel aus gespeichert link:prepare-upgrade-controllers-task.html["Controller-Upgrades vorbereiten"]ist. Informationen zur Verwendung dieses Befehls finden Sie im https://docs.netapp.com/us-en/e-series-cli/index.html["Referenz für Befehlszeilenschnittstelle"].
+
*Beispiel:* `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
Alternativ können Sie den internen Schlüssel über die Rest-API über den folgenden Aufruf importieren: `/storage-systems/{system-id}/security-key/import`



Die Controller werden mit der Synchronisierung von Autocodes von den Laufwerken fortgesetzt und neu gestartet. Nach dem Neustart können die Controller über die ursprüngliche IP-Konfiguration aufgerufen werden.



== Externes Verschlüsselungskeymanagement

Führen Sie diese Schritte für externes Verschlüsselungsmanagement aus, wenn alle Laufwerke gesperrt sind.

.Über diese Aufgabe
Die neu getauschten Controller werden mit einem siebensegmentreichen Anzeigefeld von *L5* gesperrt. Diese Sperre tritt auf, wenn keine Laufwerke die Autocodierung (ACS) durchführen können. Nach dem Import des Sicherheitsschlüssels wird ACS die neuen Controller wieder aufgenommen und aktualisiert.

.Schritte
. Stellen Sie eine direkte, private ethernet-Verbindung zwischen dem Speicher-Array und dem Laptop oder PC des SANtricity-Clients her. Dazu:
+
.. Verwenden Sie ein RJ45-ethernet-Kabel, um den Laptop mit dem Verwaltungsport 1 an Controller A zu verbinden
.. Um die Verbindung abzuschließen, müssen Sie den Laptop möglicherweise einer IP-Adresse im selben Subnetz zuweisen wie Controller A. während der Controller-Sperrung wird Controller A standardmäßig auf die Managementadresse 169.254.128.101 gesetzt. Sie können den Laptop also einem Subnetz wie „169.254.128.201“ zuweisen.


. link:prepare-upgrade-controllers-task.html["Controller-Upgrades vorbereiten"]Importieren Sie den externen Schlüssel mit dem von gespeicherten Sicherheitsschlüssel in die IP-Adresse 169.254.128.101, wobei der Benutzername *admin* und das Passwort leer bleiben.
+
*Beispiel:* `SMcli 169.254.128.101 -k -u admin -p "" -c "import storageArray securityKey file=\"Directory&FileName\" passPhrase=\"passPhraseString\";"`

+
Alternativ können Sie den externen Schlüssel über die Rest-API über den folgenden Aufruf importieren: `/storage-systems/{system-id}/security-key/import`

+
Die Controller werden mit der Synchronisierung von Autocodes von den Laufwerken fortgesetzt und neu gestartet. Nach dem Neustart können die Controller über die ursprüngliche IP-Konfiguration aufgerufen werden.

. (Optional) bei Bedarf können die Laufwerke mit einem Rekeying neu coden, indem Sie die folgenden Schritte ausführen:
+
*Beispiel:* `SMcli <original_controller _ip> -u admin -p "<original_array_password>" -c "create storageArray securityKey" passPhrase=\"passPhraseString\" file=\"filename\";”`


